{{- if and (include "aura.isSelfHosted" .) .Values.databases.document.postgres.enabled }}
{{- if not .Values.databases.document.postgres.existingPasswordSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aura.fullname" . }}-postgres
  labels:
    {{- include "aura.componentLabels" (dict "component" "postgres" "context" .) | nindent 4 }}
type: Opaque
data:
  {{- if .Values.databases.document.postgres.password }}
  postgres-password: {{ .Values.databases.document.postgres.password | b64enc | quote }}
  {{- else }}
  postgres-password: {{ randAlphaNum 24 | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
