/**
 * Project Aura - DiagramViewer Component
 *
 * Interactive architecture diagram viewer with pan/zoom, theme support,
 * and export capabilities. Renders SVG diagrams generated by the backend
 * diagram service (ADR-060).
 *
 * Design System: Apple-inspired with clean typography, generous spacing,
 * and smooth transitions per design-principles.md
 */

import { useState, useEffect, useRef, useCallback, useMemo } from 'react';
import { useTheme } from '../../context/ThemeContext';
import {
  MagnifyingGlassPlusIcon,
  MagnifyingGlassMinusIcon,
  ArrowsPointingOutIcon,
  ArrowDownTrayIcon,
  SunIcon,
  MoonIcon,
  DocumentDuplicateIcon,
  PhotoIcon,
  ArrowPathIcon,
  EyeIcon,
  EyeSlashIcon,
  AdjustmentsHorizontalIcon,
} from '@heroicons/react/24/outline';

// ============================================================================
// Constants & Configuration
// ============================================================================

const MIN_ZOOM = 0.1;
const MAX_ZOOM = 4.0;
const ZOOM_STEP = 0.25;
const ZOOM_ANIMATION_DURATION = 200;

const EXPORT_FORMATS = {
  svg: { label: 'SVG', extension: '.svg', mimeType: 'image/svg+xml' },
  png: { label: 'PNG', extension: '.png', mimeType: 'image/png' },
};

// ============================================================================
// DiagramToolbar Component
// ============================================================================

function DiagramToolbar({
  zoom,
  onZoomIn,
  onZoomOut,
  onFitToView,
  onResetView,
  onExport,
  onToggleTheme,
  isDarkTheme,
  showGrid,
  onToggleGrid,
  isExporting,
}) {
  const [showExportMenu, setShowExportMenu] = useState(false);
  const exportMenuRef = useRef(null);

  // Close export menu on outside click
  useEffect(() => {
    function handleClickOutside(event) {
      if (exportMenuRef.current && !exportMenuRef.current.contains(event.target)) {
        setShowExportMenu(false);
      }
    }
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  const buttonClass = `
    p-2 rounded-lg
    bg-surface-100 dark:bg-surface-700
    hover:bg-surface-200 dark:hover:bg-surface-600
    border border-surface-200 dark:border-surface-600
    transition-all duration-200 ease-smooth
    focus:outline-none focus:ring-2 focus:ring-aura-500
    disabled:opacity-50 disabled:cursor-not-allowed
  `;

  return (
    <div
      className="
        flex items-center gap-2 px-3 py-2
        bg-white/90 dark:bg-surface-800/90
        backdrop-blur-sm
        border border-surface-200 dark:border-surface-700
        rounded-xl shadow-lg
      "
      role="toolbar"
      aria-label="Diagram controls"
    >
      {/* Zoom Controls */}
      <div className="flex items-center gap-1 border-r border-surface-200 dark:border-surface-600 pr-2">
        <button
          onClick={onZoomOut}
          disabled={zoom <= MIN_ZOOM}
          className={buttonClass}
          title="Zoom out (Ctrl+-)"
          aria-label="Zoom out"
        >
          <MagnifyingGlassMinusIcon className="w-5 h-5 text-surface-600 dark:text-surface-300" />
        </button>

        <span
          className="
            min-w-[4rem] text-center text-sm font-medium
            text-surface-700 dark:text-surface-200
          "
          aria-live="polite"
        >
          {Math.round(zoom * 100)}%
        </span>

        <button
          onClick={onZoomIn}
          disabled={zoom >= MAX_ZOOM}
          className={buttonClass}
          title="Zoom in (Ctrl++)"
          aria-label="Zoom in"
        >
          <MagnifyingGlassPlusIcon className="w-5 h-5 text-surface-600 dark:text-surface-300" />
        </button>
      </div>

      {/* View Controls */}
      <div className="flex items-center gap-1 border-r border-surface-200 dark:border-surface-600 pr-2">
        <button
          onClick={onFitToView}
          className={buttonClass}
          title="Fit to view (Ctrl+0)"
          aria-label="Fit diagram to view"
        >
          <ArrowsPointingOutIcon className="w-5 h-5 text-surface-600 dark:text-surface-300" />
        </button>

        <button
          onClick={onResetView}
          className={buttonClass}
          title="Reset view (Ctrl+1)"
          aria-label="Reset view to 100%"
        >
          <ArrowPathIcon className="w-5 h-5 text-surface-600 dark:text-surface-300" />
        </button>
      </div>

      {/* Display Options */}
      <div className="flex items-center gap-1 border-r border-surface-200 dark:border-surface-600 pr-2">
        <button
          onClick={onToggleGrid}
          className={`${buttonClass} ${showGrid ? 'bg-aura-100 dark:bg-aura-900/30' : ''}`}
          title={showGrid ? 'Hide grid' : 'Show grid'}
          aria-label={showGrid ? 'Hide grid' : 'Show grid'}
          aria-pressed={showGrid}
        >
          {showGrid ? (
            <EyeIcon className="w-5 h-5 text-aura-600 dark:text-aura-400" />
          ) : (
            <EyeSlashIcon className="w-5 h-5 text-surface-600 dark:text-surface-300" />
          )}
        </button>

        <button
          onClick={onToggleTheme}
          className={buttonClass}
          title={isDarkTheme ? 'Switch to light theme' : 'Switch to dark theme'}
          aria-label={isDarkTheme ? 'Switch to light theme' : 'Switch to dark theme'}
        >
          {isDarkTheme ? (
            <SunIcon className="w-5 h-5 text-warning-400" />
          ) : (
            <MoonIcon className="w-5 h-5 text-aura-600" />
          )}
        </button>
      </div>

      {/* Export Menu */}
      <div className="relative" ref={exportMenuRef}>
        <button
          onClick={() => setShowExportMenu(!showExportMenu)}
          disabled={isExporting}
          className={`${buttonClass} flex items-center gap-2`}
          title="Export diagram"
          aria-label="Export diagram"
          aria-expanded={showExportMenu}
          aria-haspopup="menu"
        >
          {isExporting ? (
            <ArrowPathIcon className="w-5 h-5 text-surface-600 dark:text-surface-300 animate-spin" />
          ) : (
            <ArrowDownTrayIcon className="w-5 h-5 text-surface-600 dark:text-surface-300" />
          )}
          <span className="text-sm font-medium text-surface-700 dark:text-surface-200">
            Export
          </span>
        </button>

        {showExportMenu && (
          <div
            className="
              absolute right-0 top-full mt-2 w-48
              bg-white dark:bg-surface-800
              border border-surface-200 dark:border-surface-700
              rounded-lg shadow-xl
              overflow-hidden
              z-50
            "
            role="menu"
          >
            <button
              onClick={() => {
                onExport('svg');
                setShowExportMenu(false);
              }}
              className="
                flex items-center gap-3 w-full px-4 py-3
                hover:bg-surface-100 dark:hover:bg-surface-700
                transition-colors duration-150
              "
              role="menuitem"
            >
              <DocumentDuplicateIcon className="w-5 h-5 text-aura-600 dark:text-aura-400" />
              <span className="text-sm text-surface-700 dark:text-surface-200">
                Export as SVG
              </span>
            </button>
            <button
              onClick={() => {
                onExport('png');
                setShowExportMenu(false);
              }}
              className="
                flex items-center gap-3 w-full px-4 py-3
                hover:bg-surface-100 dark:hover:bg-surface-700
                transition-colors duration-150
              "
              role="menuitem"
            >
              <PhotoIcon className="w-5 h-5 text-success-600 dark:text-success-400" />
              <span className="text-sm text-surface-700 dark:text-surface-200">
                Export as PNG
              </span>
            </button>
          </div>
        )}
      </div>
    </div>
  );
}

// ============================================================================
// DiagramCanvas Component
// ============================================================================

function DiagramCanvas({
  svgContent,
  zoom,
  pan,
  onPanChange,
  showGrid,
  isDarkTheme,
  containerRef,
}) {
  const canvasRef = useRef(null);
  const [isDragging, setIsDragging] = useState(false);
  const [dragStart, setDragStart] = useState({ x: 0, y: 0 });

  // Handle mouse wheel zoom
  const handleWheel = useCallback(
    (e) => {
      if (e.ctrlKey || e.metaKey) {
        e.preventDefault();
        const delta = e.deltaY > 0 ? -ZOOM_STEP : ZOOM_STEP;
        const newZoom = Math.max(MIN_ZOOM, Math.min(MAX_ZOOM, zoom + delta));
        // Zoom towards mouse position
        if (containerRef.current) {
          const rect = containerRef.current.getBoundingClientRect();
          const mouseX = e.clientX - rect.left;
          const mouseY = e.clientY - rect.top;
          const scale = newZoom / zoom;
          onPanChange({
            x: mouseX - (mouseX - pan.x) * scale,
            y: mouseY - (mouseY - pan.y) * scale,
          });
        }
      }
    },
    [zoom, pan, onPanChange, containerRef]
  );

  // Handle drag start
  const handleMouseDown = useCallback(
    (e) => {
      if (e.button === 0) {
        setIsDragging(true);
        setDragStart({ x: e.clientX - pan.x, y: e.clientY - pan.y });
      }
    },
    [pan]
  );

  // Handle drag move
  const handleMouseMove = useCallback(
    (e) => {
      if (isDragging) {
        onPanChange({
          x: e.clientX - dragStart.x,
          y: e.clientY - dragStart.y,
        });
      }
    },
    [isDragging, dragStart, onPanChange]
  );

  // Handle drag end
  const handleMouseUp = useCallback(() => {
    setIsDragging(false);
  }, []);

  // Set up event listeners
  useEffect(() => {
    const container = containerRef.current;
    if (container) {
      container.addEventListener('wheel', handleWheel, { passive: false });
      return () => container.removeEventListener('wheel', handleWheel);
    }
  }, [handleWheel, containerRef]);

  // Grid pattern
  const gridPattern = useMemo(() => {
    if (!showGrid) return null;
    const gridSize = 20 * zoom;
    const gridColor = isDarkTheme ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.05)';
    return `
      <pattern id="grid" width="${gridSize}" height="${gridSize}" patternUnits="userSpaceOnUse">
        <path d="M ${gridSize} 0 L 0 0 0 ${gridSize}" fill="none" stroke="${gridColor}" stroke-width="1"/>
      </pattern>
      <rect width="100%" height="100%" fill="url(#grid)"/>
    `;
  }, [showGrid, zoom, isDarkTheme]);

  return (
    <div
      ref={canvasRef}
      className={`
        relative w-full h-full overflow-hidden
        ${isDragging ? 'cursor-grabbing' : 'cursor-grab'}
      `}
      onMouseDown={handleMouseDown}
      onMouseMove={handleMouseMove}
      onMouseUp={handleMouseUp}
      onMouseLeave={handleMouseUp}
      role="img"
      aria-label="Architecture diagram viewer"
    >
      {/* Background with grid */}
      <svg
        className="absolute inset-0 w-full h-full pointer-events-none"
        aria-hidden="true"
      >
        <defs dangerouslySetInnerHTML={{ __html: gridPattern || '' }} />
        {showGrid && <rect width="100%" height="100%" fill="url(#grid)" />}
      </svg>

      {/* Diagram content */}
      <div
        className="absolute origin-top-left transition-transform duration-75"
        style={{
          transform: `translate(${pan.x}px, ${pan.y}px) scale(${zoom})`,
        }}
        dangerouslySetInnerHTML={{ __html: svgContent }}
      />
    </div>
  );
}

// ============================================================================
// Main DiagramViewer Component
// ============================================================================

export default function DiagramViewer({
  svgContent,
  title = 'Architecture Diagram',
  initialZoom = 1.0,
  onExportComplete,
  className = '',
}) {
  const { isDarkMode } = useTheme();
  const containerRef = useRef(null);

  // State
  const [zoom, setZoom] = useState(initialZoom);
  const [pan, setPan] = useState({ x: 0, y: 0 });
  const [diagramTheme, setDiagramTheme] = useState(isDarkMode ? 'dark' : 'light');
  const [showGrid, setShowGrid] = useState(false);
  const [isExporting, setIsExporting] = useState(false);
  const [svgDimensions, setSvgDimensions] = useState({ width: 0, height: 0 });

  // Parse SVG dimensions
  useEffect(() => {
    if (svgContent) {
      const parser = new DOMParser();
      const doc = parser.parseFromString(svgContent, 'image/svg+xml');
      const svg = doc.querySelector('svg');
      if (svg) {
        const viewBox = svg.getAttribute('viewBox');
        if (viewBox) {
          const [, , w, h] = viewBox.split(' ').map(Number);
          setSvgDimensions({ width: w, height: h });
        } else {
          setSvgDimensions({
            width: parseFloat(svg.getAttribute('width')) || 800,
            height: parseFloat(svg.getAttribute('height')) || 600,
          });
        }
      }
    }
  }, [svgContent]);

  // Sync diagram theme with app theme
  useEffect(() => {
    setDiagramTheme(isDarkMode ? 'dark' : 'light');
  }, [isDarkMode]);

  // Keyboard shortcuts
  useEffect(() => {
    function handleKeyDown(e) {
      if (e.ctrlKey || e.metaKey) {
        switch (e.key) {
          case '+':
          case '=':
            e.preventDefault();
            handleZoomIn();
            break;
          case '-':
            e.preventDefault();
            handleZoomOut();
            break;
          case '0':
            e.preventDefault();
            handleFitToView();
            break;
          case '1':
            e.preventDefault();
            handleResetView();
            break;
          default:
            break;
        }
      }
    }
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [zoom]);

  // Zoom handlers
  const handleZoomIn = useCallback(() => {
    setZoom((z) => Math.min(MAX_ZOOM, z + ZOOM_STEP));
  }, []);

  const handleZoomOut = useCallback(() => {
    setZoom((z) => Math.max(MIN_ZOOM, z - ZOOM_STEP));
  }, []);

  const handleFitToView = useCallback(() => {
    if (containerRef.current && svgDimensions.width && svgDimensions.height) {
      const container = containerRef.current;
      const containerWidth = container.clientWidth;
      const containerHeight = container.clientHeight;
      const padding = 40;

      const scaleX = (containerWidth - padding * 2) / svgDimensions.width;
      const scaleY = (containerHeight - padding * 2) / svgDimensions.height;
      const newZoom = Math.min(scaleX, scaleY, MAX_ZOOM);

      const newX = (containerWidth - svgDimensions.width * newZoom) / 2;
      const newY = (containerHeight - svgDimensions.height * newZoom) / 2;

      setZoom(newZoom);
      setPan({ x: newX, y: newY });
    }
  }, [svgDimensions]);

  const handleResetView = useCallback(() => {
    setZoom(1.0);
    setPan({ x: 0, y: 0 });
  }, []);

  // Theme toggle
  const handleToggleTheme = useCallback(() => {
    setDiagramTheme((t) => (t === 'dark' ? 'light' : 'dark'));
  }, []);

  // Export handler
  const handleExport = useCallback(
    async (format) => {
      if (!svgContent) return;

      setIsExporting(true);
      try {
        const filename = `${title.toLowerCase().replace(/\s+/g, '-')}-${Date.now()}`;

        if (format === 'svg') {
          // Export as SVG
          const blob = new Blob([svgContent], { type: 'image/svg+xml' });
          const url = URL.createObjectURL(blob);
          const a = document.createElement('a');
          a.href = url;
          a.download = `${filename}.svg`;
          document.body.appendChild(a);
          a.click();
          document.body.removeChild(a);
          URL.revokeObjectURL(url);
        } else if (format === 'png') {
          // Export as PNG
          const canvas = document.createElement('canvas');
          const scale = 2; // Higher resolution
          canvas.width = svgDimensions.width * scale;
          canvas.height = svgDimensions.height * scale;
          const ctx = canvas.getContext('2d');

          const img = new Image();
          const svgBlob = new Blob([svgContent], { type: 'image/svg+xml;charset=utf-8' });
          const svgUrl = URL.createObjectURL(svgBlob);

          await new Promise((resolve, reject) => {
            img.onload = () => {
              ctx.fillStyle = diagramTheme === 'dark' ? '#1E293B' : '#FFFFFF';
              ctx.fillRect(0, 0, canvas.width, canvas.height);
              ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
              resolve();
            };
            img.onerror = reject;
            img.src = svgUrl;
          });

          URL.revokeObjectURL(svgUrl);

          const pngUrl = canvas.toDataURL('image/png');
          const a = document.createElement('a');
          a.href = pngUrl;
          a.download = `${filename}.png`;
          document.body.appendChild(a);
          a.click();
          document.body.removeChild(a);
        }

        onExportComplete?.(format);
      } catch (error) {
        console.error('Export failed:', error);
      } finally {
        setIsExporting(false);
      }
    },
    [svgContent, title, svgDimensions, diagramTheme, onExportComplete]
  );

  // Apply diagram theme to SVG content
  const themedSvgContent = useMemo(() => {
    if (!svgContent) return '';
    // The backend renders with the requested theme, so we just return as-is
    // Future: Could apply CSS filters for theme switching without re-rendering
    return svgContent;
  }, [svgContent]);

  // Empty state
  if (!svgContent) {
    return (
      <div
        className={`
          flex flex-col items-center justify-center
          min-h-[400px] p-8
          bg-surface-50 dark:bg-surface-900
          border border-surface-200 dark:border-surface-700
          rounded-xl
          ${className}
        `}
      >
        <AdjustmentsHorizontalIcon
          className="w-16 h-16 text-surface-300 dark:text-surface-600 mb-4"
          aria-hidden="true"
        />
        <h3 className="text-lg font-semibold text-surface-700 dark:text-surface-200 mb-2">
          No Diagram to Display
        </h3>
        <p className="text-sm text-surface-500 dark:text-surface-400 text-center max-w-md">
          Generate an architecture diagram using natural language or the DSL editor
          to visualize your infrastructure.
        </p>
      </div>
    );
  }

  return (
    <div
      className={`
        relative flex flex-col
        bg-surface-100 dark:bg-surface-900
        border border-surface-200 dark:border-surface-700
        rounded-xl overflow-hidden
        ${className}
      `}
    >
      {/* Header */}
      <div
        className="
          flex items-center justify-between
          px-4 py-3
          bg-white dark:bg-surface-800
          border-b border-surface-200 dark:border-surface-700
        "
      >
        <h2 className="text-lg font-semibold text-surface-900 dark:text-surface-100">
          {title}
        </h2>

        <DiagramToolbar
          zoom={zoom}
          onZoomIn={handleZoomIn}
          onZoomOut={handleZoomOut}
          onFitToView={handleFitToView}
          onResetView={handleResetView}
          onExport={handleExport}
          onToggleTheme={handleToggleTheme}
          isDarkTheme={diagramTheme === 'dark'}
          showGrid={showGrid}
          onToggleGrid={() => setShowGrid(!showGrid)}
          isExporting={isExporting}
        />
      </div>

      {/* Canvas */}
      <div
        ref={containerRef}
        className="flex-1 min-h-[500px]"
        style={{
          backgroundColor: diagramTheme === 'dark' ? '#1E293B' : '#F8FAFC',
        }}
      >
        <DiagramCanvas
          svgContent={themedSvgContent}
          zoom={zoom}
          pan={pan}
          onPanChange={setPan}
          showGrid={showGrid}
          isDarkTheme={diagramTheme === 'dark'}
          containerRef={containerRef}
        />
      </div>

      {/* Status Bar */}
      <div
        className="
          flex items-center justify-between
          px-4 py-2
          bg-white dark:bg-surface-800
          border-t border-surface-200 dark:border-surface-700
          text-xs text-surface-500 dark:text-surface-400
        "
      >
        <span>
          {svgDimensions.width} x {svgDimensions.height} px
        </span>
        <span>
          Pan: ({Math.round(pan.x)}, {Math.round(pan.y)}) | Zoom: {Math.round(zoom * 100)}%
        </span>
      </div>
    </div>
  );
}

// ============================================================================
// Named Exports for Subcomponents
// ============================================================================

export { DiagramToolbar, DiagramCanvas };
