"""
Transform Agent Services - AWS Transform Agent Parity

This module provides comprehensive legacy modernization capabilities
replicating AWS Transform Agent functionality:

- COBOL Parser: Enterprise COBOL code analysis and parsing
- .NET Parser: .NET Framework/Core code analysis
- Cross-Language Translator: Intelligent code translation between languages
- Architecture Reimaginer: Architecture modernization and redesign
- Transform Agent Orchestrator: Unified modernization workflow automation

Reference: ADR-030 Section 5.4 Transform Agent Components
"""

from .architecture_reimaginer import (
    ArchitectureAssessment,
    ArchitecturePattern,
    ArchitectureReimaginer,
    ArchitectureStyle,
    CloudProvider,
    CloudServiceMapping,
    CommunicationPattern,
    ComponentType,
    CurrentArchitecture,
    DatabaseType,
    DataConsistencyPattern,
    DataStore,
    DeploymentPattern,
    InfrastructureRecommendation,
    Integration,
    MicroserviceCandidate,
    MigrationPhase,
    MigrationRisk,
    MigrationRoadmap,
    ModernizationStrategy,
    Priority,
    RiskLevel,
    ScalabilityPattern,
    SecurityRecommendation,
    ServiceDecomposition,
    SystemComponent,
    TargetArchitecture,
    TechnologyStack,
)
from .cobol_parser import (
    AccessMode,
    CICSCommand,
    COBOLDivision,
    COBOLParser,
    COBOLProgram,
    Complexity,
    Copybook,
    DataFlow,
    DataItem,
    DataItemType,
    DataSection,
    FileDefinition,
    FileOrganization,
    Paragraph,
)
from .cobol_parser import ParseError as COBOLParseError
from .cobol_parser import ParseResult as COBOLParseResult
from .cobol_parser import (
    PictureCategory,
    PictureClause,
    ProgramDependency,
    Section,
    SQLStatement,
    Statement,
    StatementType,
)
from .cross_language_translator import (
    ComplexityLevel,
    ConfidenceLevel,
    CrossLanguageTranslator,
    DataStructureTranslation,
    DataTypeMapping,
    FunctionTranslation,
    ImportStatement,
    ManualReviewItem,
    SourceLanguage,
    TargetLanguage,
    TranslatedFile,
    TranslationConfig,
    TranslationResult,
    TranslationStatus,
    TranslationStrategy,
    TranslationTestCase,
    TranslationWarning,
    TypeMapping,
    VariableTranslation,
)
from .dotnet_parser import (
    AccessModifier,
    ApiEndpoint,
    AssemblyReference,
    Attribute,
    DatabaseAccess,
    DetectedPattern,
    DotNetLanguage,
    DotNetParser,
    DotNetProject,
    DotNetSolution,
    EventInfo,
    FieldInfo,
    FrameworkType,
    GenericParameter,
    LegacyPattern,
    MemberType,
    MethodInfo,
    NuGetPackage,
    Parameter,
)
from .dotnet_parser import ParseError as DotNetParseError
from .dotnet_parser import ParseResult as DotNetParseResult
from .dotnet_parser import (
    PatternType,
    ProjectReference,
    ProjectType,
    PropertyInfo,
    SourceFile,
    TypeDefinition,
    TypeKind,
    UsingDirective,
)
from .transform_agent_orchestrator import (
    AnalysisReport,
    LegacyCodebase,
    LegacyPlatform,
    ModernizationRecommendation,
    TargetPlatform,
    TransformAgentOrchestrator,
    TransformationArtifact,
    TransformationScope,
    TransformStatus,
    TransformWorkflowResult,
    TransformWorkflowType,
    TranslationSummary,
    ValidationResult,
)

__all__ = [
    # COBOL Parser
    "COBOLParser",
    "COBOLProgram",
    "COBOLDivision",
    "DataItem",
    "DataItemType",
    "DataSection",
    "Paragraph",
    "Section",
    "Statement",
    "StatementType",
    "SQLStatement",
    "CICSCommand",
    "Copybook",
    "FileDefinition",
    "ProgramDependency",
    "DataFlow",
    "PictureClause",
    "PictureCategory",
    "FileOrganization",
    "AccessMode",
    "Complexity",
    "COBOLParseResult",
    "COBOLParseError",
    # .NET Parser
    "DotNetParser",
    "DotNetProject",
    "DotNetSolution",
    "SourceFile",
    "TypeDefinition",
    "TypeKind",
    "MethodInfo",
    "PropertyInfo",
    "FieldInfo",
    "EventInfo",
    "Parameter",
    "GenericParameter",
    "Attribute",
    "UsingDirective",
    "NuGetPackage",
    "ProjectReference",
    "AssemblyReference",
    "ApiEndpoint",
    "DatabaseAccess",
    "DetectedPattern",
    "PatternType",
    "LegacyPattern",
    "DotNetLanguage",
    "FrameworkType",
    "ProjectType",
    "MemberType",
    "AccessModifier",
    "DotNetParseResult",
    "DotNetParseError",
    # Cross-Language Translator
    "CrossLanguageTranslator",
    "TranslationConfig",
    "TranslationResult",
    "TranslatedFile",
    "TranslationTestCase",
    "VariableTranslation",
    "FunctionTranslation",
    "DataStructureTranslation",
    "TypeMapping",
    "ImportStatement",
    "TranslationWarning",
    "ManualReviewItem",
    "SourceLanguage",
    "TargetLanguage",
    "TranslationStrategy",
    "DataTypeMapping",
    "ComplexityLevel",
    "TranslationStatus",
    "ConfidenceLevel",
    # Architecture Reimaginer
    "ArchitectureReimaginer",
    "ArchitectureAssessment",
    "CurrentArchitecture",
    "TargetArchitecture",
    "SystemComponent",
    "DataStore",
    "Integration",
    "MicroserviceCandidate",
    "ServiceDecomposition",
    "CloudServiceMapping",
    "InfrastructureRecommendation",
    "SecurityRecommendation",
    "MigrationRisk",
    "MigrationPhase",
    "MigrationRoadmap",
    "ArchitecturePattern",
    "TechnologyStack",
    "ArchitectureStyle",
    "CloudProvider",
    "ModernizationStrategy",
    "ComponentType",
    "DatabaseType",
    "CommunicationPattern",
    "ScalabilityPattern",
    "DataConsistencyPattern",
    "DeploymentPattern",
    "RiskLevel",
    "Priority",
    # Transform Agent Orchestrator
    "TransformAgentOrchestrator",
    "TransformWorkflowResult",
    "TransformWorkflowType",
    "TransformStatus",
    "TransformationScope",
    "LegacyCodebase",
    "AnalysisReport",
    "TranslationSummary",
    "ModernizationRecommendation",
    "TransformationArtifact",
    "ValidationResult",
    "LegacyPlatform",
    "TargetPlatform",
]
