"""HopRAG Service for Multi-Hop Query Optimization

Implements ADR-034 Phase 2.2: HopRAG Integration

Based on HopRAG paper (arXiv:2502.12442):
- Pseudo-query edge generation during indexing
- Multi-hop graph traversal with logic-aware retrieval
- Retrieve-reason-prune pipeline

Research shows:
- 65.07% improved retrieval F1
- 76.78% higher answer accuracy on complex queries
"""

import json
import logging
import math
from dataclasses import dataclass, field
from typing import Optional, Protocol

from src.services.neptune_graph_service import escape_gremlin_string
from src.services.rlm.input_sanitizer import InputSanitizer

logger = logging.getLogger(__name__)

# SECURITY: Input sanitizer for LLM prompt construction to prevent context poisoning
_input_sanitizer = InputSanitizer()


class NeptuneClient(Protocol):
    """Protocol for Neptune client."""

    async def execute(self, query: str) -> list:
        """Execute Gremlin query."""
        ...


class LLMClient(Protocol):
    """Protocol for LLM client."""

    async def generate(self, prompt: str, agent: str = "", operation: str = "") -> str:
        """Generate text from prompt."""
        ...


class EmbeddingService(Protocol):
    """Protocol for embedding service."""

    async def embed_text(self, text: str) -> list[float]:
        """Generate embedding for text."""
        ...

    async def embed_batch(self, texts: list[str]) -> list[list[float]]:
        """Generate embeddings for multiple texts in a single call."""
        ...


@dataclass
class PseudoQueryEdge:
    """Edge generated by LLM representing a potential query path.

    Pseudo-query edges encode the natural language question that
    would lead from source to target entity, enabling semantic
    graph traversal.
    """

    source_id: str
    target_id: str
    pseudo_query: str  # e.g., "What functions call this validation method?"
    confidence: float
    edge_type: str  # "calls", "imports", "extends", "implements"


@dataclass
class HopResult:
    """Result from multi-hop retrieval."""

    path: list[str]  # Node IDs in traversal path
    entities: list[dict]  # Entity details
    reasoning: str  # LLM reasoning chain
    confidence: float
    hops: int
    pseudo_queries_used: list[str] = field(default_factory=list)


@dataclass
class HopRAGConfig:
    """Configuration for HopRAG service."""

    max_hops: int = 3
    prune_threshold: float = 0.5
    similarity_threshold: float = 0.5
    max_neighbors: int = 10
    max_start_entities: int = 5
    embedding_cache_size: int = 1000


class HopRAGService:
    """Multi-hop retrieval service using pseudo-query edges.

    Key innovations from HopRAG research:

    1. Pseudo-query edges: LLM-generated edges representing potential queries
       - Created during code indexing phase
       - Encode semantic relationships as natural language
       - Enable semantic graph traversal

    2. Logic-aware retrieval: Traversal follows reasoning patterns
       - Query-guided neighbor selection
       - Semantic similarity matching against pseudo-queries

    3. Retrieve-reason-prune pipeline:
       - Retrieve: Get neighbors via pseudo-query edges
       - Reason: LLM selects best neighbor
       - Prune: Stop if confidence drops below threshold

    Integration with existing architecture:
    - Pseudo-query edges stored in Neptune as edge properties
    - Uses existing embedding service for similarity
    - LLM reasoning via BedrockLLMService
    """

    def __init__(
        self,
        neptune_client: NeptuneClient,
        llm_client: LLMClient,
        embedding_service: EmbeddingService,
        config: Optional[HopRAGConfig] = None,
    ):
        """Initialize HopRAG service.

        Args:
            neptune_client: Client for Neptune Gremlin queries
            llm_client: Client for LLM generation
            embedding_service: Service for generating embeddings
            config: HopRAG configuration
        """
        self.neptune = neptune_client
        self.llm = llm_client
        self.embedder = embedding_service
        self.config = config or HopRAGConfig()
        self._embedding_cache: dict[str, list[float]] = {}

    async def multi_hop_retrieve(
        self,
        query: str,
        start_entities: Optional[list[str]] = None,
        max_results: int = 20,
    ) -> list[HopResult]:
        """Execute multi-hop retrieval for complex queries.

        Args:
            query: Complex query requiring multi-hop reasoning
            start_entities: Optional starting points (auto-detected if None)
            max_results: Maximum results to return

        Returns:
            List of HopResult with traversal paths and reasoning
        """
        logger.info(f"Starting multi-hop retrieval for: {query[:100]}...")

        # Step 1: Identify starting entities if not provided
        if not start_entities:
            start_entities = await self._identify_start_entities(query)
            logger.debug(f"Identified start entities: {start_entities}")

        if not start_entities:
            logger.warning("No start entities found for query")
            return []

        # Step 2: Execute retrieve-reason-prune loop for each start
        results = []
        for start_entity in start_entities[: self.config.max_start_entities]:
            try:
                hop_result = await self._traverse_with_reasoning(
                    query, start_entity, current_hop=0
                )
                if hop_result and hop_result.confidence > self.config.prune_threshold:
                    results.append(hop_result)
            except Exception as e:
                logger.warning(f"Traversal from {start_entity} failed: {e}")
                continue

        # Step 3: Rank and return top results
        results.sort(key=lambda x: x.confidence, reverse=True)

        logger.info(
            f"Multi-hop retrieval complete: {len(results)} results "
            f"from {len(start_entities)} starting points"
        )

        return results[:max_results]

    async def _identify_start_entities(self, query: str) -> list[str]:
        """Identify starting entities for traversal using LLM.

        Args:
            query: Query to analyze

        Returns:
            List of entity IDs to start traversal from
        """
        prompt = f"""Given this query about code, identify the most likely starting entities.

Query: {query}

List entity names that should be the starting point for searching (e.g., class names,
function names, file names). Return as JSON array of strings.

Example response: ["AuthService", "validateToken", "user_controller.py"]

Response:"""

        try:
            response = await self.llm.generate(
                prompt, agent="HopRAG", operation="entity_identification"
            )

            # Parse JSON response
            entities = json.loads(response.strip())
            if isinstance(entities, list):
                return [str(e) for e in entities[:10]]
            return []

        except json.JSONDecodeError as e:
            logger.warning(f"Failed to parse entity identification response: {e}")
            # Fallback: extract capitalized words from query
            words = query.split()
            return [w for w in words if len(w) > 2 and w[0].isupper()][:5]
        except Exception as e:
            logger.warning(f"Entity identification failed: {e}")
            return []

    async def _traverse_with_reasoning(
        self,
        query: str,
        current_entity: str,
        current_hop: int,
        path: Optional[list[str]] = None,
        pseudo_queries: Optional[list[str]] = None,
    ) -> Optional[HopResult]:
        """Traverse graph with LLM reasoning at each hop.

        Implements retrieve-reason-prune:
        1. Retrieve neighbors via pseudo-query edges
        2. Reason about relevance to query
        3. Prune low-confidence paths

        Args:
            query: Original query
            current_entity: Current node in traversal
            current_hop: Current hop number
            path: Path taken so far
            pseudo_queries: Pseudo-queries used so far

        Returns:
            HopResult or None if pruned
        """
        path = path or [current_entity]
        pseudo_queries = pseudo_queries or []

        # Base case: max hops reached
        if current_hop >= self.config.max_hops:
            return HopResult(
                path=path,
                entities=await self._get_entity_details(path),
                reasoning="Max hops reached",
                confidence=0.5,
                hops=current_hop,
                pseudo_queries_used=pseudo_queries,
            )

        # Step 1: Retrieve - Get neighbors via pseudo-query edges
        neighbors = await self._get_pseudo_query_neighbors(current_entity, query)

        if not neighbors:
            return HopResult(
                path=path,
                entities=await self._get_entity_details(path),
                reasoning="No relevant neighbors found",
                confidence=0.3,
                hops=current_hop,
                pseudo_queries_used=pseudo_queries,
            )

        # Step 2: Reason - Use LLM to select best neighbor
        best_neighbor, reasoning, confidence, pq = await self._reason_about_neighbors(
            query, current_entity, neighbors, path
        )

        # Step 3: Prune - Stop if confidence too low
        if confidence < self.config.prune_threshold:
            return HopResult(
                path=path,
                entities=await self._get_entity_details(path),
                reasoning=reasoning,
                confidence=confidence,
                hops=current_hop,
                pseudo_queries_used=pseudo_queries,
            )

        # Continue traversal
        new_path = path + [best_neighbor]
        new_pqs = pseudo_queries + ([pq] if pq else [])

        return await self._traverse_with_reasoning(
            query, best_neighbor, current_hop + 1, new_path, new_pqs
        )

    async def _get_pseudo_query_neighbors(
        self, entity_id: str, query: str
    ) -> list[dict]:
        """Get neighbors connected by relevant pseudo-query edges.

        Args:
            entity_id: Current entity ID
            query: Original query for relevance filtering

        Returns:
            List of neighbor info with pseudo-queries
        """
        # Query Neptune for edges with pseudo_query property
        # SECURITY: Escape entity_id to prevent Gremlin injection attacks
        safe_entity_id = escape_gremlin_string(entity_id)
        gremlin_query = f"""
        g.V().has('name', '{safe_entity_id}')
            .bothE()
            .has('pseudo_query')
            .project('neighbor', 'pseudo_query', 'confidence', 'edge_type')
                .by(otherV().values('name'))
                .by('pseudo_query')
                .by(coalesce(values('confidence'), constant(0.5)))
                .by(label())
        """

        try:
            results = await self.neptune.execute(gremlin_query)

            if not results:
                # Fallback: get any connected nodes
                fallback_query = f"""
                g.V().has('name', '{safe_entity_id}')
                    .both()
                    .dedup()
                    .limit({self.config.max_neighbors})
                    .project('neighbor', 'type')
                        .by('name')
                        .by(label())
                """
                fallback_results = await self.neptune.execute(fallback_query)
                return [
                    {
                        "neighbor": r["neighbor"],
                        "pseudo_query": f"What is related to {entity_id}?",
                        "confidence": 0.5,
                        "edge_type": "related",
                        "similarity": 0.5,
                    }
                    for r in fallback_results
                ]

            # Filter by semantic similarity to query using batch embeddings
            # Optimized: single batch call instead of N+1 individual calls
            pseudo_queries = [r.get("pseudo_query", "") for r in results]
            texts_to_embed = [query] + pseudo_queries
            all_embeddings = await self._get_embeddings_batch(texts_to_embed)

            query_embedding = all_embeddings[0]
            pq_embeddings = all_embeddings[1:]

            scored_neighbors = []
            for result, pq_embedding in zip(results, pq_embeddings):
                similarity = self._cosine_similarity(query_embedding, pq_embedding)

                if similarity > self.config.similarity_threshold:
                    scored_neighbors.append(
                        {
                            **result,
                            "similarity": similarity,
                        }
                    )

            # Sort by similarity
            scored_neighbors.sort(key=lambda x: x["similarity"], reverse=True)
            return scored_neighbors[: self.config.max_neighbors]

        except Exception as e:
            logger.warning(f"Failed to get pseudo-query neighbors: {e}")
            return []

    async def _reason_about_neighbors(
        self,
        query: str,
        current: str,
        neighbors: list[dict],
        path: list[str],
    ) -> tuple[str, str, float, str]:
        """Use LLM to reason about which neighbor to follow.

        Args:
            query: Original query
            current: Current entity
            neighbors: Available neighbors with pseudo-queries
            path: Path taken so far

        Returns:
            Tuple of (neighbor_id, reasoning, confidence, pseudo_query)
        """
        neighbors_desc = "\n".join(
            [
                f"- {n['neighbor']}: {n['pseudo_query']} (similarity: {n['similarity']:.2f})"
                for n in neighbors[:5]
            ]
        )

        prompt = f"""You are reasoning about a code graph traversal.

Query: {query}

Current path: {' -> '.join(path)}

Possible next steps:
{neighbors_desc}

Which neighbor should we explore next to answer the query?
Consider the relevance of each pseudo-query to the original question.

Respond with JSON:
{{"neighbor": "entity_name", "reasoning": "why this path", "confidence": 0.0-1.0}}

Response:"""

        try:
            response = await self.llm.generate(
                prompt, agent="HopRAG", operation="path_reasoning"
            )

            result = json.loads(response.strip())
            neighbor = result.get("neighbor", neighbors[0]["neighbor"])
            reasoning = result.get("reasoning", "")
            confidence = float(result.get("confidence", 0.5))

            # Find the pseudo-query for this neighbor
            pq = ""
            for n in neighbors:
                if n["neighbor"] == neighbor:
                    pq = n.get("pseudo_query", "")
                    break

            return (neighbor, reasoning, confidence, pq)

        except (json.JSONDecodeError, KeyError, IndexError) as e:
            logger.warning(f"Failed to parse reasoning response: {e}")
            if neighbors:
                return (
                    neighbors[0]["neighbor"],
                    "Default selection",
                    0.5,
                    neighbors[0].get("pseudo_query", ""),
                )
            return ("", "No neighbors", 0.0, "")

    async def generate_pseudo_query_edges(
        self,
        source_id: str,
        target_id: str,
        relationship_type: str,
        source_content: Optional[str] = None,
        target_content: Optional[str] = None,
    ) -> PseudoQueryEdge:
        """Generate pseudo-query edge during indexing.

        Called during code ingestion to create HopRAG edges.

        Args:
            source_id: Source entity ID
            target_id: Target entity ID
            relationship_type: Type of relationship (calls, imports, etc.)
            source_content: Optional source entity content
            target_content: Optional target entity content

        Returns:
            Generated PseudoQueryEdge
        """
        # SECURITY: Sanitize source_id and target_id to prevent GraphRAG context poisoning
        # These IDs come from code entities which could contain malicious content
        source_id_result = _input_sanitizer.sanitize_task(source_id)
        target_id_result = _input_sanitizer.sanitize_task(target_id)
        relationship_result = _input_sanitizer.sanitize_task(relationship_type)

        safe_source_id = source_id_result.sanitized_text
        safe_target_id = target_id_result.sanitized_text
        safe_relationship = relationship_result.sanitized_text

        # Sanitize content snippets if provided
        safe_source_content = ""
        safe_target_content = ""
        if source_content:
            # Truncate and sanitize content to prevent prompt injection
            truncated = source_content[:200]
            content_result = _input_sanitizer.sanitize_task(truncated)
            if content_result.is_safe:
                safe_source_content = f" ({content_result.sanitized_text}...)"
        if target_content:
            truncated = target_content[:200]
            content_result = _input_sanitizer.sanitize_task(truncated)
            if content_result.is_safe:
                safe_target_content = f" ({content_result.sanitized_text}...)"

        prompt = f"""Generate a natural language query that would lead from source to target.

Source: {safe_source_id}{safe_source_content}
Target: {safe_target_id}{safe_target_content}
Relationship: {safe_relationship}

What question would someone ask that requires understanding this relationship?
Respond with just the query text, nothing else.

Query:"""

        try:
            pseudo_query = await self.llm.generate(
                prompt, agent="HopRAG_Indexer", operation="edge_generation"
            )
            pseudo_query = pseudo_query.strip()
        except Exception as e:
            logger.warning(f"Failed to generate pseudo-query: {e}")
            pseudo_query = f"What {safe_relationship} {safe_source_id}?"

        return PseudoQueryEdge(
            source_id=source_id,
            target_id=target_id,
            pseudo_query=pseudo_query,
            confidence=0.8,
            edge_type=relationship_type,
        )

    async def store_pseudo_query_edge(self, edge: PseudoQueryEdge) -> bool:
        """Store pseudo-query edge in Neptune.

        Args:
            edge: PseudoQueryEdge to store

        Returns:
            True if successful
        """
        # SECURITY: Escape all string values to prevent Gremlin injection attacks
        safe_source_id = escape_gremlin_string(edge.source_id)
        safe_target_id = escape_gremlin_string(edge.target_id)
        safe_edge_type = escape_gremlin_string(edge.edge_type)
        safe_pseudo_query = escape_gremlin_string(edge.pseudo_query)

        gremlin_query = f"""
        g.V().has('name', '{safe_source_id}')
            .outE('{safe_edge_type}')
            .where(inV().has('name', '{safe_target_id}'))
            .property('pseudo_query', '{safe_pseudo_query}')
            .property('confidence', {edge.confidence})
        """

        try:
            await self.neptune.execute(gremlin_query)
            return True
        except Exception as e:
            logger.error(f"Failed to store pseudo-query edge: {e}")
            return False

    async def _get_entity_details(self, entity_ids: list[str]) -> list[dict]:
        """Get detailed information about entities.

        Args:
            entity_ids: List of entity IDs

        Returns:
            List of entity detail dictionaries
        """
        if not entity_ids:
            return []

        # SECURITY: Escape all entity IDs to prevent Gremlin injection attacks
        safe_entity_ids = [escape_gremlin_string(e) for e in entity_ids]
        names_str = ", ".join(f"'{e}'" for e in safe_entity_ids)
        gremlin_query = f"""
        g.V().has('name', within({names_str}))
            .project('id', 'name', 'type', 'content', 'file_path')
                .by(id())
                .by('name')
                .by(label())
                .by(coalesce(values('content'), constant('')))
                .by(coalesce(values('file_path'), constant('')))
        """

        try:
            return await self.neptune.execute(gremlin_query)
        except Exception as e:
            logger.warning(f"Failed to get entity details: {e}")
            return [{"name": e, "type": "unknown"} for e in entity_ids]

    async def _get_embedding(self, text: str) -> list[float]:
        """Get embedding with caching.

        Args:
            text: Text to embed

        Returns:
            Embedding vector
        """
        cache_key = text[:500]  # Truncate for cache key
        if cache_key in self._embedding_cache:
            return self._embedding_cache[cache_key]

        embedding = await self.embedder.embed_text(text)

        # Simple LRU-like cache management
        if len(self._embedding_cache) >= self.config.embedding_cache_size:
            # Remove oldest entry
            oldest_key = next(iter(self._embedding_cache))
            del self._embedding_cache[oldest_key]

        self._embedding_cache[cache_key] = embedding
        return embedding

    async def _get_embeddings_batch(self, texts: list[str]) -> list[list[float]]:
        """Get embeddings for multiple texts with caching.

        Optimized to batch embed uncached texts in a single API call,
        reducing N API calls to 1 for N texts.

        Args:
            texts: List of texts to embed

        Returns:
            List of embedding vectors in same order as input texts
        """
        results: list[list[float] | None] = [None] * len(texts)
        uncached_indices: list[int] = []
        uncached_texts: list[str] = []

        # Check cache for each text
        for i, text in enumerate(texts):
            cache_key = text[:500]
            if cache_key in self._embedding_cache:
                results[i] = self._embedding_cache[cache_key]
            else:
                uncached_indices.append(i)
                uncached_texts.append(text)

        # Batch embed uncached texts if any
        if uncached_texts:
            try:
                embeddings = await self.embedder.embed_batch(uncached_texts)

                for idx, (i, text) in enumerate(zip(uncached_indices, uncached_texts)):
                    embedding = embeddings[idx]
                    results[i] = embedding

                    # Cache the embedding
                    cache_key = text[:500]
                    if len(self._embedding_cache) >= self.config.embedding_cache_size:
                        oldest_key = next(iter(self._embedding_cache))
                        del self._embedding_cache[oldest_key]
                    self._embedding_cache[cache_key] = embedding

            except AttributeError:
                # Fallback if embed_batch not available - use individual calls
                for i, text in zip(uncached_indices, uncached_texts):
                    embedding = await self._get_embedding(text)
                    results[i] = embedding

        return [r if r is not None else [] for r in results]

    def _cosine_similarity(self, vec1: list[float], vec2: list[float]) -> float:
        """Compute cosine similarity.

        Args:
            vec1: First vector
            vec2: Second vector

        Returns:
            Cosine similarity score
        """
        if not vec1 or not vec2 or len(vec1) != len(vec2):
            return 0.0

        dot = sum(a * b for a, b in zip(vec1, vec2))
        norm1 = math.sqrt(sum(a * a for a in vec1))
        norm2 = math.sqrt(sum(b * b for b in vec2))

        if norm1 == 0 or norm2 == 0:
            return 0.0

        return dot / (norm1 * norm2)

    def get_service_stats(self) -> dict:
        """Get service statistics.

        Returns:
            Statistics dictionary
        """
        return {
            "embedding_cache_size": len(self._embedding_cache),
            "max_cache_size": self.config.embedding_cache_size,
            "config": {
                "max_hops": self.config.max_hops,
                "prune_threshold": self.config.prune_threshold,
                "similarity_threshold": self.config.similarity_threshold,
            },
        }

    def clear_cache(self) -> None:
        """Clear embedding cache."""
        self._embedding_cache.clear()
