/**
 * Widget Registry - Catalog of available dashboard widgets
 *
 * Defines all available widgets with metadata for the dashboard
 * customization system per ADR-064.
 */

// Widget Types
export const WidgetType = {
  METRIC: 'metric',
  CHART_LINE: 'chart_line',
  CHART_BAR: 'chart_bar',
  CHART_DONUT: 'chart_donut',
  TABLE: 'table',
  STATUS_GRID: 'status_grid',
  ACTIVITY_FEED: 'activity_feed',
  GAUGE: 'gauge',
  PROGRESS: 'progress',
};

// Widget Categories
export const WidgetCategory = {
  SECURITY: 'security',
  OPERATIONS: 'operations',
  ANALYTICS: 'analytics',
  COMPLIANCE: 'compliance',
  COST: 'cost',
  THREAT_INTELLIGENCE: 'threat_intelligence',
  SUPPLY_CHAIN: 'supply_chain',
  RUNTIME_SECURITY: 'runtime_security',
  AIRGAP_EDGE: 'airgap_edge',
  AI_SECURITY: 'ai_security',
  VULNERABILITY_SCANNER: 'vulnerability_scanner',
};

// User Roles for defaults
export const UserRole = {
  SECURITY_ENGINEER: 'security-engineer',
  DEVOPS: 'devops',
  ENGINEERING_MANAGER: 'engineering-manager',
  EXECUTIVE: 'executive',
  SUPERUSER: 'superuser',
  COMPLIANCE_OFFICER: 'compliance-officer',
};

// Widget Definitions Catalog
export const WIDGET_CATALOG = [
  // Security Widgets
  {
    id: 'open-vulnerabilities',
    type: WidgetType.METRIC,
    category: WidgetCategory.SECURITY,
    name: 'Open Vulnerabilities',
    description: 'Count of currently open security vulnerabilities',
    dataSource: 'security/vulnerabilities/open',
    defaultRefreshSeconds: 60,
    supportsSparkline: true,
    supportsTrend: true,
    minWidth: 1,
    minHeight: 2,
    defaultWidth: 3,
    defaultHeight: 2,
    defaultColor: 'critical',
  },
  {
    id: 'mttr',
    type: WidgetType.METRIC,
    category: WidgetCategory.SECURITY,
    name: 'Mean Time to Remediate',
    description: 'Average time to fix vulnerabilities (in hours)',
    dataSource: 'security/metrics/mttr',
    defaultRefreshSeconds: 300,
    supportsSparkline: true,
    supportsTrend: true,
    minWidth: 1,
    minHeight: 2,
    defaultWidth: 3,
    defaultHeight: 2,
    defaultColor: 'aura',
  },
  {
    id: 'cve-trend',
    type: WidgetType.CHART_LINE,
    category: WidgetCategory.SECURITY,
    name: 'CVE Trend',
    description: '30-day trend of CVE discoveries and patches',
    dataSource: 'security/cve/trend',
    defaultRefreshSeconds: 300,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 3,
    minHeight: 2,
    defaultWidth: 6,
    defaultHeight: 3,
    defaultColor: 'aura',
  },
  {
    id: 'recent-alerts',
    type: WidgetType.ACTIVITY_FEED,
    category: WidgetCategory.SECURITY,
    name: 'Recent Security Alerts',
    description: 'Latest security alerts and notifications',
    dataSource: 'security/alerts/recent',
    defaultRefreshSeconds: 30,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 3,
    minHeight: 3,
    defaultWidth: 6,
    defaultHeight: 3,
    defaultColor: 'critical',
  },
  // Operations Widgets
  {
    id: 'pending-approvals',
    type: WidgetType.METRIC,
    category: WidgetCategory.OPERATIONS,
    name: 'Pending Approvals',
    description: 'Number of items awaiting HITL approval',
    dataSource: 'approvals/pending/count',
    defaultRefreshSeconds: 30,
    supportsSparkline: true,
    supportsTrend: true,
    minWidth: 1,
    minHeight: 2,
    defaultWidth: 3,
    defaultHeight: 2,
    defaultColor: 'warning',
  },
  {
    id: 'agent-health-grid',
    type: WidgetType.STATUS_GRID,
    category: WidgetCategory.OPERATIONS,
    name: 'Agent Health Grid',
    description: 'Health status of all active agents',
    dataSource: 'agents/health/grid',
    defaultRefreshSeconds: 30,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 3,
    minHeight: 2,
    defaultWidth: 6,
    defaultHeight: 3,
    defaultColor: 'aura',
  },
  {
    id: 'sandbox-utilization',
    type: WidgetType.GAUGE,
    category: WidgetCategory.OPERATIONS,
    name: 'Sandbox Utilization',
    description: 'Current sandbox environment utilization percentage',
    dataSource: 'environments/sandbox/utilization',
    defaultRefreshSeconds: 60,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 2,
    minHeight: 2,
    defaultWidth: 3,
    defaultHeight: 2,
    defaultColor: 'aura',
  },
  {
    id: 'environment-status',
    type: WidgetType.STATUS_GRID,
    category: WidgetCategory.OPERATIONS,
    name: 'Environment Status',
    description: 'Status of dev/qa/prod environments',
    dataSource: 'environments/status',
    defaultRefreshSeconds: 60,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 2,
    minHeight: 2,
    defaultWidth: 3,
    defaultHeight: 2,
    defaultColor: 'olive',
  },
  {
    id: 'gpu-jobs-queued',
    type: WidgetType.METRIC,
    category: WidgetCategory.OPERATIONS,
    name: 'GPU Jobs Queued',
    description: 'Number of GPU jobs waiting in queue',
    dataSource: 'gpu/jobs/queued',
    defaultRefreshSeconds: 30,
    supportsSparkline: true,
    supportsTrend: true,
    minWidth: 1,
    minHeight: 2,
    defaultWidth: 3,
    defaultHeight: 2,
    defaultColor: 'warning',
  },
  {
    id: 'deployment-velocity',
    type: WidgetType.METRIC,
    category: WidgetCategory.OPERATIONS,
    name: 'Deployment Velocity',
    description: 'Deployments per day (7-day average)',
    dataSource: 'deployments/velocity',
    defaultRefreshSeconds: 300,
    supportsSparkline: true,
    supportsTrend: true,
    minWidth: 1,
    minHeight: 2,
    defaultWidth: 3,
    defaultHeight: 2,
    defaultColor: 'olive',
  },
  // Analytics Widgets
  {
    id: 'code-quality-score',
    type: WidgetType.METRIC,
    category: WidgetCategory.ANALYTICS,
    name: 'Code Quality Score',
    description: 'Overall code quality score (0-100)',
    dataSource: 'analytics/code-quality/score',
    defaultRefreshSeconds: 300,
    supportsSparkline: true,
    supportsTrend: true,
    minWidth: 1,
    minHeight: 2,
    defaultWidth: 3,
    defaultHeight: 2,
    defaultColor: 'aura',
  },
  {
    id: 'test-coverage-trend',
    type: WidgetType.CHART_LINE,
    category: WidgetCategory.ANALYTICS,
    name: 'Test Coverage Trend',
    description: 'Test coverage percentage over time',
    dataSource: 'analytics/test-coverage/trend',
    defaultRefreshSeconds: 300,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 3,
    minHeight: 2,
    defaultWidth: 6,
    defaultHeight: 3,
    defaultColor: 'olive',
  },
  {
    id: 'pr-velocity-by-team',
    type: WidgetType.CHART_BAR,
    category: WidgetCategory.ANALYTICS,
    name: 'PR Velocity by Team',
    description: 'Pull request velocity grouped by team',
    dataSource: 'analytics/pr/velocity-by-team',
    defaultRefreshSeconds: 300,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 3,
    minHeight: 2,
    defaultWidth: 6,
    defaultHeight: 3,
    defaultColor: 'aura',
  },
  // Compliance Widgets
  {
    id: 'compliance-progress',
    type: WidgetType.PROGRESS,
    category: WidgetCategory.COMPLIANCE,
    name: 'Compliance Progress',
    description: 'Overall compliance readiness percentage',
    dataSource: 'compliance/progress',
    defaultRefreshSeconds: 300,
    supportsSparkline: false,
    supportsTrend: true,
    minWidth: 2,
    minHeight: 2,
    defaultWidth: 4,
    defaultHeight: 2,
    defaultColor: 'aura',
  },
  {
    id: 'risk-posture-score',
    type: WidgetType.GAUGE,
    category: WidgetCategory.COMPLIANCE,
    name: 'Risk Posture Score',
    description: 'Composite risk posture score (0-100)',
    dataSource: 'security/risk-posture',
    defaultRefreshSeconds: 300,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 2,
    minHeight: 2,
    defaultWidth: 4,
    defaultHeight: 2,
    defaultColor: 'olive',
  },
  {
    id: 'key-incidents',
    type: WidgetType.TABLE,
    category: WidgetCategory.COMPLIANCE,
    name: 'Key Incidents',
    description: 'Recent key security incidents',
    dataSource: 'incidents/recent',
    defaultRefreshSeconds: 60,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 4,
    minHeight: 3,
    defaultWidth: 12,
    defaultHeight: 3,
    defaultColor: 'critical',
  },
  // Cost Widgets
  {
    id: 'monthly-cost',
    type: WidgetType.METRIC,
    category: WidgetCategory.COST,
    name: 'Monthly Cost',
    description: 'Current month infrastructure cost',
    dataSource: 'cost/monthly-summary',
    defaultRefreshSeconds: 3600,
    supportsSparkline: true,
    supportsTrend: true,
    minWidth: 2,
    minHeight: 2,
    defaultWidth: 4,
    defaultHeight: 2,
    defaultColor: 'surface',
  },
  {
    id: 'cost-trend',
    type: WidgetType.CHART_LINE,
    category: WidgetCategory.COST,
    name: 'Cost Trend',
    description: '30-day infrastructure cost trend',
    dataSource: 'cost/trend',
    defaultRefreshSeconds: 3600,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 4,
    minHeight: 2,
    defaultWidth: 6,
    defaultHeight: 3,
    defaultColor: 'aura',
  },
  // Palantir AIP Widgets (ADR-075)
  {
    id: 'palantir-active-threats',
    type: WidgetType.ACTIVITY_FEED,
    category: WidgetCategory.THREAT_INTELLIGENCE,
    name: 'Active Threat Campaigns',
    description: 'Real-time threat campaigns from Palantir AIP',
    dataSource: 'palantir/threats/active',
    component: 'ThreatIntelWidget',
    defaultRefreshSeconds: 60,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 2,
    minHeight: 2,
    defaultWidth: 4,
    defaultHeight: 3,
    defaultColor: 'critical',
    requiredIntegration: 'palantir_aip',
    requiredRoles: ['security-engineer', 'superuser'],
  },
  {
    id: 'palantir-sync-status',
    type: WidgetType.STATUS_GRID,
    category: WidgetCategory.OPERATIONS,
    name: 'Ontology Sync Health',
    description: 'Palantir Ontology object sync status and circuit breaker state',
    dataSource: 'palantir/sync/status',
    component: 'SyncStatusWidget',
    defaultRefreshSeconds: 30,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 2,
    minHeight: 2,
    defaultWidth: 4,
    defaultHeight: 3,
    defaultColor: 'aura',
    requiredIntegration: 'palantir_aip',
    requiredRoles: ['security-engineer', 'devops', 'superuser'],
  },
  {
    id: 'palantir-cve-prioritization',
    type: WidgetType.TABLE,
    category: WidgetCategory.SECURITY,
    name: 'Prioritized Vulnerabilities',
    description: 'CVEs ranked by EPSS + asset criticality + active threat',
    dataSource: 'palantir/threats/context',
    component: 'PrioritizedVulnsWidget',
    defaultRefreshSeconds: 300,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 2,
    minHeight: 3,
    defaultWidth: 4,
    defaultHeight: 4,
    defaultColor: 'critical',
    requiredIntegration: 'palantir_aip',
    requiredRoles: ['security-engineer', 'superuser'],
  },
  {
    id: 'palantir-asset-criticality',
    type: WidgetType.TABLE,
    category: WidgetCategory.OPERATIONS,
    name: 'Asset Criticality',
    description: 'Repository criticality scores from Palantir CMDB',
    dataSource: 'palantir/assets/criticality',
    component: 'AssetCriticalityWidget',
    defaultRefreshSeconds: 3600,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 2,
    minHeight: 2,
    defaultWidth: 4,
    defaultHeight: 3,
    defaultColor: 'surface',
    requiredIntegration: 'palantir_aip',
    requiredRoles: ['security-engineer', 'devops', 'superuser'],
  },
  {
    id: 'palantir-epss-trend',
    type: WidgetType.CHART_LINE,
    category: WidgetCategory.ANALYTICS,
    name: 'EPSS Score Trends',
    description: '30-day EPSS percentile trends (P50/P95/P99)',
    dataSource: 'palantir/epss/trend',
    component: 'EPSSTrendWidget',
    defaultRefreshSeconds: 300,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 3,
    minHeight: 2,
    defaultWidth: 6,
    defaultHeight: 3,
    defaultColor: 'aura',
    requiredIntegration: 'palantir_aip',
    requiredRoles: ['security-engineer', 'superuser'],
  },
  {
    id: 'palantir-compliance-drift',
    type: WidgetType.PROGRESS,
    category: WidgetCategory.COMPLIANCE,
    name: 'Compliance Drift',
    description: 'Compliance control failures requiring remediation',
    dataSource: 'palantir/compliance/drift',
    component: 'ComplianceDriftWidget',
    defaultRefreshSeconds: 300,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 2,
    minHeight: 2,
    defaultWidth: 4,
    defaultHeight: 4,
    defaultColor: 'warning',
    requiredIntegration: 'palantir_aip',
    requiredRoles: ['compliance-officer', 'security-engineer', 'superuser'],
  },
  {
    id: 'palantir-insider-risk',
    type: WidgetType.METRIC,
    category: WidgetCategory.SECURITY,
    name: 'Insider Risk',
    description: 'Count of users with elevated risk scores',
    dataSource: 'palantir/insider/risk',
    component: 'InsiderRiskWidget',
    defaultRefreshSeconds: 300,
    supportsSparkline: false,
    supportsTrend: true,
    minWidth: 1,
    minHeight: 2,
    defaultWidth: 3,
    defaultHeight: 2,
    defaultColor: 'critical',
    requiredIntegration: 'palantir_aip',
    requiredRoles: ['security-engineer', 'superuser'],
  },
  {
    id: 'palantir-mttr',
    type: WidgetType.GAUGE,
    category: WidgetCategory.ANALYTICS,
    name: 'MTTR (Palantir)',
    description: 'Mean Time to Remediation with severity breakdown',
    dataSource: 'palantir/metrics/mttr',
    component: 'MTTRWidget',
    defaultRefreshSeconds: 300,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 1,
    minHeight: 2,
    defaultWidth: 3,
    defaultHeight: 3,
    defaultColor: 'aura',
    requiredIntegration: 'palantir_aip',
    requiredRoles: ['security-engineer', 'devops', 'superuser'],
  },
  // ADR-076: Supply Chain Security Widgets
  {
    id: 'supply-chain-sbom-status',
    type: WidgetType.STATUS_GRID,
    category: WidgetCategory.SUPPLY_CHAIN,
    name: 'SBOM Generation Status',
    description: 'Software bill of materials generation and validation status',
    dataSource: 'supply-chain/sbom/status',
    component: 'SBOMStatusWidget',
    defaultRefreshSeconds: 300,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 2,
    minHeight: 2,
    defaultWidth: 4,
    defaultHeight: 3,
    defaultColor: 'aura',
    requiredRoles: ['security-engineer', 'devops', 'superuser'],
  },
  {
    id: 'supply-chain-dependency-confusion',
    type: WidgetType.ACTIVITY_FEED,
    category: WidgetCategory.SUPPLY_CHAIN,
    name: 'Dependency Confusion Alerts',
    description: 'Alerts for potential dependency confusion attacks',
    dataSource: 'supply-chain/dependency-confusion/alerts',
    component: 'DependencyConfusionWidget',
    defaultRefreshSeconds: 60,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 2,
    minHeight: 2,
    defaultWidth: 4,
    defaultHeight: 3,
    defaultColor: 'critical',
    requiredRoles: ['security-engineer', 'superuser'],
  },
  {
    id: 'supply-chain-license-compliance',
    type: WidgetType.CHART_DONUT,
    category: WidgetCategory.SUPPLY_CHAIN,
    name: 'License Compliance',
    description: 'Distribution of dependency licenses by risk category',
    dataSource: 'supply-chain/licenses/compliance',
    component: 'LicenseComplianceWidget',
    defaultRefreshSeconds: 3600,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 2,
    minHeight: 2,
    defaultWidth: 4,
    defaultHeight: 3,
    defaultColor: 'olive',
    requiredRoles: ['security-engineer', 'compliance-officer', 'superuser'],
  },
  {
    id: 'supply-chain-attestation',
    type: WidgetType.STATUS_GRID,
    category: WidgetCategory.SUPPLY_CHAIN,
    name: 'Attestation Status',
    description: 'SLSA and in-toto attestation verification status',
    dataSource: 'supply-chain/attestation/status',
    component: 'AttestationStatusWidget',
    defaultRefreshSeconds: 300,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 2,
    minHeight: 2,
    defaultWidth: 4,
    defaultHeight: 3,
    defaultColor: 'aura',
    requiredRoles: ['security-engineer', 'devops', 'superuser'],
  },
  // ADR-077: Runtime Security Widgets
  {
    id: 'runtime-admission-decisions',
    type: WidgetType.CHART_BAR,
    category: WidgetCategory.RUNTIME_SECURITY,
    name: 'Admission Decisions',
    description: 'Container admission controller allow/deny statistics',
    dataSource: 'runtime/admission/decisions',
    component: 'AdmissionDecisionsWidget',
    defaultRefreshSeconds: 60,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 2,
    minHeight: 2,
    defaultWidth: 4,
    defaultHeight: 3,
    defaultColor: 'aura',
    requiredRoles: ['security-engineer', 'devops', 'superuser'],
  },
  {
    id: 'runtime-container-escape',
    type: WidgetType.ACTIVITY_FEED,
    category: WidgetCategory.RUNTIME_SECURITY,
    name: 'Container Escape Detection',
    description: 'Real-time container escape attempt detection with MITRE ATT&CK mapping',
    dataSource: 'runtime/container-escape/alerts',
    component: 'ContainerEscapeWidget',
    defaultRefreshSeconds: 30,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 2,
    minHeight: 2,
    defaultWidth: 4,
    defaultHeight: 3,
    defaultColor: 'critical',
    requiredRoles: ['security-engineer', 'superuser'],
  },
  {
    id: 'runtime-correlation',
    type: WidgetType.TABLE,
    category: WidgetCategory.RUNTIME_SECURITY,
    name: 'Runtime Correlation',
    description: 'Correlated security events across network, process, and file activity',
    dataSource: 'runtime/correlation/events',
    component: 'RuntimeCorrelationWidget',
    defaultRefreshSeconds: 60,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 3,
    minHeight: 2,
    defaultWidth: 6,
    defaultHeight: 3,
    defaultColor: 'warning',
    requiredRoles: ['security-engineer', 'superuser'],
  },
  {
    id: 'runtime-guardduty-findings',
    type: WidgetType.ACTIVITY_FEED,
    category: WidgetCategory.RUNTIME_SECURITY,
    name: 'GuardDuty Findings',
    description: 'AWS GuardDuty security findings and threat detections',
    dataSource: 'runtime/guardduty/findings',
    component: 'GuardDutyFindingsWidget',
    defaultRefreshSeconds: 60,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 2,
    minHeight: 2,
    defaultWidth: 4,
    defaultHeight: 3,
    defaultColor: 'critical',
    requiredRoles: ['security-engineer', 'devops', 'superuser'],
  },
  // ADR-083: Runtime Agent Security Platform Widgets
  {
    id: 'runtime-red-team-block-rate',
    type: WidgetType.GAUGE,
    category: WidgetCategory.RUNTIME_SECURITY,
    name: 'Red Team Block Rate',
    description: 'Percentage of automated adversarial attacks blocked by security controls',
    dataSource: 'runtime-security/red-team/block-rate',
    component: 'RedTeamBlockRateWidget',
    defaultRefreshSeconds: 300,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 2,
    minHeight: 2,
    defaultWidth: 3,
    defaultHeight: 2,
    defaultColor: 'olive',
    requiredRoles: ['security-engineer', 'superuser'],
  },
  {
    id: 'runtime-shadow-agents',
    type: WidgetType.METRIC,
    category: WidgetCategory.RUNTIME_SECURITY,
    name: 'Shadow Agents Detected',
    description: 'Unregistered agents discovered via traffic analysis',
    dataSource: 'runtime-security/discovery/shadow-agents',
    component: 'ShadowAgentsWidget',
    defaultRefreshSeconds: 60,
    supportsSparkline: true,
    supportsTrend: true,
    minWidth: 1,
    minHeight: 2,
    defaultWidth: 3,
    defaultHeight: 2,
    defaultColor: 'critical',
    requiredRoles: ['security-engineer', 'superuser'],
  },
  {
    id: 'runtime-behavioral-anomalies',
    type: WidgetType.ACTIVITY_FEED,
    category: WidgetCategory.RUNTIME_SECURITY,
    name: 'Behavioral Anomalies',
    description: 'Recent behavioral deviations detected by baseline engine',
    dataSource: 'runtime-security/baselines/anomalies',
    component: 'BehavioralAnomaliesWidget',
    defaultRefreshSeconds: 30,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 3,
    minHeight: 3,
    defaultWidth: 6,
    defaultHeight: 3,
    defaultColor: 'warning',
    requiredRoles: ['security-engineer', 'devops', 'superuser'],
  },
  {
    id: 'runtime-correlation-rate',
    type: WidgetType.GAUGE,
    category: WidgetCategory.RUNTIME_SECURITY,
    name: 'Correlation Rate',
    description: 'Percentage of runtime events correlated to source code root causes',
    dataSource: 'runtime-security/correlation/rate',
    component: 'CorrelationRateWidget',
    defaultRefreshSeconds: 300,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 2,
    minHeight: 2,
    defaultWidth: 3,
    defaultHeight: 2,
    defaultColor: 'aura',
    requiredRoles: ['security-engineer', 'superuser'],
  },
  {
    id: 'runtime-red-team-by-category',
    type: WidgetType.CHART_BAR,
    category: WidgetCategory.RUNTIME_SECURITY,
    name: 'Red Team Results by Category',
    description: 'Attack test outcomes grouped by AURA-ATT&CK category',
    dataSource: 'runtime-security/red-team/by-category',
    component: 'RedTeamByCategoryWidget',
    defaultRefreshSeconds: 300,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 3,
    minHeight: 2,
    defaultWidth: 6,
    defaultHeight: 3,
    defaultColor: 'aura',
    requiredRoles: ['security-engineer', 'superuser'],
  },
  {
    id: 'runtime-agent-traffic-volume',
    type: WidgetType.CHART_LINE,
    category: WidgetCategory.RUNTIME_SECURITY,
    name: 'Agent Traffic Volume',
    description: 'Agent traffic events captured over time (24h trend)',
    dataSource: 'runtime-security/interceptor/volume-trend',
    component: 'AgentTrafficVolumeWidget',
    defaultRefreshSeconds: 300,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 3,
    minHeight: 2,
    defaultWidth: 6,
    defaultHeight: 3,
    defaultColor: 'aura',
    requiredRoles: ['security-engineer', 'devops', 'superuser'],
  },
  {
    id: 'runtime-agent-traffic-by-type',
    type: WidgetType.CHART_DONUT,
    category: WidgetCategory.RUNTIME_SECURITY,
    name: 'Agent Traffic by Type',
    description: 'Distribution of agent traffic by event type',
    dataSource: 'runtime-security/interceptor/by-type',
    component: 'AgentTrafficByTypeWidget',
    defaultRefreshSeconds: 300,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 3,
    minHeight: 2,
    defaultWidth: 4,
    defaultHeight: 3,
    defaultColor: 'aura',
    requiredRoles: ['security-engineer', 'devops', 'superuser'],
  },
  // ADR-078: Air-Gapped & Edge Deployment Widgets
  {
    id: 'airgap-bundle-status',
    type: WidgetType.STATUS_GRID,
    category: WidgetCategory.AIRGAP_EDGE,
    name: 'Bundle Transfer Status',
    description: 'Air-gapped deployment bundle creation and transfer status',
    dataSource: 'airgap/bundles/status',
    component: 'BundleStatusWidget',
    defaultRefreshSeconds: 300,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 2,
    minHeight: 2,
    defaultWidth: 4,
    defaultHeight: 3,
    defaultColor: 'aura',
    requiredRoles: ['devops', 'security-engineer', 'superuser'],
  },
  {
    id: 'airgap-firmware-analysis',
    type: WidgetType.TABLE,
    category: WidgetCategory.AIRGAP_EDGE,
    name: 'Firmware Analysis',
    description: 'Edge device firmware vulnerability analysis results',
    dataSource: 'airgap/firmware/analysis',
    component: 'FirmwareAnalysisWidget',
    defaultRefreshSeconds: 3600,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 3,
    minHeight: 2,
    defaultWidth: 6,
    defaultHeight: 3,
    defaultColor: 'warning',
    requiredRoles: ['security-engineer', 'superuser'],
  },
  {
    id: 'airgap-edge-health',
    type: WidgetType.STATUS_GRID,
    category: WidgetCategory.AIRGAP_EDGE,
    name: 'Edge Runtime Health',
    description: 'Health status of edge deployment nodes',
    dataSource: 'airgap/edge/health',
    component: 'EdgeRuntimeHealthWidget',
    defaultRefreshSeconds: 60,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 2,
    minHeight: 2,
    defaultWidth: 4,
    defaultHeight: 3,
    defaultColor: 'olive',
    requiredRoles: ['devops', 'superuser'],
  },
  {
    id: 'airgap-egress-validation',
    type: WidgetType.ACTIVITY_FEED,
    category: WidgetCategory.AIRGAP_EDGE,
    name: 'Egress Validation',
    description: 'Network egress validation and blocked connection attempts',
    dataSource: 'airgap/egress/validation',
    component: 'EgressValidationWidget',
    defaultRefreshSeconds: 30,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 2,
    minHeight: 2,
    defaultWidth: 4,
    defaultHeight: 3,
    defaultColor: 'critical',
    requiredRoles: ['security-engineer', 'devops', 'superuser'],
  },
  // ADR-079: Scale & AI Security Widgets
  {
    id: 'ai-security-streaming-latency',
    type: WidgetType.CHART_LINE,
    category: WidgetCategory.AI_SECURITY,
    name: 'Streaming Latency',
    description: 'P50/P95/P99 analysis latency percentiles with trend visualization',
    dataSource: 'ai-security/streaming/latency',
    component: 'StreamingLatencyWidget',
    defaultRefreshSeconds: 30,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 3,
    minHeight: 2,
    defaultWidth: 6,
    defaultHeight: 3,
    defaultColor: 'aura',
    requiredRoles: ['devops', 'security-engineer', 'superuser'],
  },
  {
    id: 'ai-security-model-access',
    type: WidgetType.ACTIVITY_FEED,
    category: WidgetCategory.AI_SECURITY,
    name: 'Model Access Anomalies',
    description: 'Model weight access anomalies and suspicious access patterns',
    dataSource: 'ai-security/model-access/anomalies',
    component: 'ModelAccessWidget',
    defaultRefreshSeconds: 60,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 2,
    minHeight: 2,
    defaultWidth: 4,
    defaultHeight: 3,
    defaultColor: 'critical',
    requiredRoles: ['security-engineer', 'superuser'],
  },
  {
    id: 'ai-security-training-poisoning',
    type: WidgetType.ACTIVITY_FEED,
    category: WidgetCategory.AI_SECURITY,
    name: 'Training Poisoning',
    description: 'Training data poisoning alerts and quarantine status',
    dataSource: 'ai-security/training/poisoning',
    component: 'TrainingPoisoningWidget',
    defaultRefreshSeconds: 60,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 2,
    minHeight: 2,
    defaultWidth: 4,
    defaultHeight: 3,
    defaultColor: 'critical',
    requiredRoles: ['security-engineer', 'superuser'],
  },
  {
    id: 'ai-security-graph-scale',
    type: WidgetType.STATUS_GRID,
    category: WidgetCategory.OPERATIONS,
    name: 'Graph Scale Health',
    description: 'Neptune graph shard health, query latency, and replication status',
    dataSource: 'ai-security/graph/health',
    component: 'GraphScaleWidget',
    defaultRefreshSeconds: 30,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 2,
    minHeight: 2,
    defaultWidth: 4,
    defaultHeight: 4,
    defaultColor: 'aura',
    requiredRoles: ['devops', 'security-engineer', 'superuser'],
  },
  // =====================================================================
  // ADR-084: Vulnerability Scanner Widgets (20 total)
  // =====================================================================
  // P0 Widgets (8)
  {
    id: 'scanner-findings-by-severity',
    type: WidgetType.CHART_BAR,
    category: WidgetCategory.VULNERABILITY_SCANNER,
    name: 'Scan Findings by Severity',
    description: 'Stacked bar chart of findings by CRITICAL/HIGH/MEDIUM/LOW/INFO',
    dataSource: 'scanner/metrics/findings-by-severity',
    component: 'FindingsBySeverityWidget',
    defaultRefreshSeconds: 60,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 3,
    minHeight: 2,
    defaultWidth: 6,
    defaultHeight: 3,
    defaultColor: 'critical',
    requiredRoles: ['security-engineer', 'devops', 'superuser'],
  },
  {
    id: 'scanner-active-scans',
    type: WidgetType.METRIC,
    category: WidgetCategory.VULNERABILITY_SCANNER,
    name: 'Active Scans',
    description: 'Count of currently running scans with pipeline stage status',
    dataSource: 'scanner/metrics/active-scans',
    component: 'ActiveScansWidget',
    defaultRefreshSeconds: 15,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 1,
    minHeight: 2,
    defaultWidth: 3,
    defaultHeight: 3,
    defaultColor: 'aura',
    requiredRoles: ['security-engineer', 'devops', 'superuser'],
  },
  {
    id: 'scanner-pipeline-progress',
    type: WidgetType.PROGRESS,
    category: WidgetCategory.VULNERABILITY_SCANNER,
    name: 'Scan Pipeline Progress',
    description: '7-segment progress bar showing per-stage status',
    dataSource: 'scanner/metrics/pipeline-progress',
    component: 'ScanPipelineProgressWidget',
    defaultRefreshSeconds: 5,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 3,
    minHeight: 2,
    defaultWidth: 6,
    defaultHeight: 3,
    defaultColor: 'aura',
    requiredRoles: ['security-engineer', 'devops', 'superuser'],
  },
  {
    id: 'scanner-true-positive-rate',
    type: WidgetType.GAUGE,
    category: WidgetCategory.VULNERABILITY_SCANNER,
    name: 'True Positive Rate',
    description: 'Percentage of verified findings that are true positives',
    dataSource: 'scanner/metrics/true-positive-rate',
    component: 'TruePositiveRateWidget',
    defaultRefreshSeconds: 300,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 2,
    minHeight: 2,
    defaultWidth: 3,
    defaultHeight: 2,
    defaultColor: 'olive',
    requiredRoles: ['security-engineer', 'superuser'],
  },
  {
    id: 'scanner-llm-token-spend',
    type: WidgetType.METRIC,
    category: WidgetCategory.VULNERABILITY_SCANNER,
    name: 'LLM Token Spend',
    description: 'Daily and monthly LLM token usage and cost',
    dataSource: 'scanner/metrics/llm-token-spend',
    component: 'LLMTokenSpendWidget',
    defaultRefreshSeconds: 60,
    supportsSparkline: false,
    supportsTrend: true,
    minWidth: 1,
    minHeight: 2,
    defaultWidth: 3,
    defaultHeight: 3,
    defaultColor: 'warning',
    requiredRoles: ['security-engineer', 'devops', 'executive', 'superuser'],
  },
  {
    id: 'scanner-alarm-status',
    type: WidgetType.STATUS_GRID,
    category: WidgetCategory.VULNERABILITY_SCANNER,
    name: 'Scanner Alarm Status',
    description: 'Health status of 5 scanner CloudWatch alarms',
    dataSource: 'scanner/metrics/alarm-status',
    component: 'ScannerAlarmStatusWidget',
    defaultRefreshSeconds: 30,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 2,
    minHeight: 2,
    defaultWidth: 3,
    defaultHeight: 3,
    defaultColor: 'aura',
    requiredRoles: ['security-engineer', 'devops', 'superuser'],
  },
  {
    id: 'scanner-recent-activity',
    type: WidgetType.ACTIVITY_FEED,
    category: WidgetCategory.VULNERABILITY_SCANNER,
    name: 'Recent Scan Activity',
    description: 'Activity feed of recent scan events, sortable and filterable',
    dataSource: 'scanner/metrics/recent-activity',
    component: 'RecentScanActivityWidget',
    defaultRefreshSeconds: 30,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 3,
    minHeight: 3,
    defaultWidth: 6,
    defaultHeight: 3,
    defaultColor: 'aura',
    requiredRoles: ['security-engineer', 'devops', 'superuser'],
  },
  {
    id: 'scanner-findings-requiring-approval',
    type: WidgetType.METRIC,
    category: WidgetCategory.VULNERABILITY_SCANNER,
    name: 'Findings Requiring Approval',
    description: 'Count of findings awaiting HITL approval with severity breakdown',
    dataSource: 'scanner/metrics/findings-requiring-approval',
    component: 'FindingsRequiringApprovalWidget',
    defaultRefreshSeconds: 30,
    supportsSparkline: false,
    supportsTrend: true,
    minWidth: 1,
    minHeight: 2,
    defaultWidth: 3,
    defaultHeight: 2,
    defaultColor: 'warning',
    requiredRoles: ['security-engineer', 'superuser'],
  },
  // P1 Widgets (7)
  {
    id: 'scanner-duration-trend',
    type: WidgetType.CHART_LINE,
    category: WidgetCategory.VULNERABILITY_SCANNER,
    name: 'Scan Duration Trend',
    description: 'Time series of average and percentile scan durations',
    dataSource: 'scanner/metrics/scan-duration-trend',
    component: 'ScanDurationTrendWidget',
    defaultRefreshSeconds: 300,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 3,
    minHeight: 2,
    defaultWidth: 6,
    defaultHeight: 3,
    defaultColor: 'aura',
    requiredRoles: ['devops', 'security-engineer', 'superuser'],
  },
  {
    id: 'scanner-stage-duration',
    type: WidgetType.CHART_BAR,
    category: WidgetCategory.VULNERABILITY_SCANNER,
    name: 'Stage Duration Waterfall',
    description: 'Time breakdown across pipeline stages',
    dataSource: 'scanner/metrics/stage-duration',
    component: 'StageDurationWaterfallWidget',
    defaultRefreshSeconds: 300,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 3,
    minHeight: 2,
    defaultWidth: 6,
    defaultHeight: 3,
    defaultColor: 'aura',
    requiredRoles: ['devops', 'security-engineer', 'superuser'],
  },
  {
    id: 'scanner-findings-by-cwe',
    type: WidgetType.CHART_BAR,
    category: WidgetCategory.VULNERABILITY_SCANNER,
    name: 'Findings by CWE',
    description: 'Horizontal bar chart of findings by CWE category',
    dataSource: 'scanner/metrics/findings-by-cwe',
    component: 'FindingsByCWEWidget',
    defaultRefreshSeconds: 300,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 3,
    minHeight: 2,
    defaultWidth: 6,
    defaultHeight: 3,
    defaultColor: 'aura',
    requiredRoles: ['security-engineer', 'superuser'],
  },
  {
    id: 'scanner-llm-latency',
    type: WidgetType.CHART_LINE,
    category: WidgetCategory.VULNERABILITY_SCANNER,
    name: 'LLM Latency',
    description: 'P50/P95/P99 LLM response latency percentiles',
    dataSource: 'scanner/metrics/llm-latency',
    component: 'LLMLatencyWidget',
    defaultRefreshSeconds: 30,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 3,
    minHeight: 2,
    defaultWidth: 6,
    defaultHeight: 3,
    defaultColor: 'warning',
    requiredRoles: ['devops', 'superuser'],
  },
  {
    id: 'scanner-concurrent-utilization',
    type: WidgetType.GAUGE,
    category: WidgetCategory.VULNERABILITY_SCANNER,
    name: 'Concurrent Scan Utilization',
    description: 'Active vs max concurrent scan capacity',
    dataSource: 'scanner/metrics/concurrent-utilization',
    component: 'ConcurrentUtilizationWidget',
    defaultRefreshSeconds: 15,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 2,
    minHeight: 2,
    defaultWidth: 3,
    defaultHeight: 2,
    defaultColor: 'aura',
    requiredRoles: ['devops', 'superuser'],
  },
  {
    id: 'scanner-critical-findings-trend',
    type: WidgetType.CHART_LINE,
    category: WidgetCategory.VULNERABILITY_SCANNER,
    name: 'Critical Findings Trend 30d',
    description: '30-day trend of critical findings per day',
    dataSource: 'scanner/metrics/critical-findings-trend',
    component: 'CriticalFindingsTrendWidget',
    defaultRefreshSeconds: 300,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 3,
    minHeight: 2,
    defaultWidth: 6,
    defaultHeight: 3,
    defaultColor: 'critical',
    requiredRoles: ['security-engineer', 'executive', 'superuser'],
  },
  {
    id: 'scanner-queue-depth',
    type: WidgetType.METRIC,
    category: WidgetCategory.VULNERABILITY_SCANNER,
    name: 'Scan Queue Depth',
    description: 'Number of scans waiting in queue',
    dataSource: 'scanner/metrics/scan-queue-depth',
    component: 'ScanQueueDepthWidget',
    defaultRefreshSeconds: 15,
    supportsSparkline: false,
    supportsTrend: true,
    minWidth: 1,
    minHeight: 2,
    defaultWidth: 3,
    defaultHeight: 2,
    defaultColor: 'surface',
    requiredRoles: ['devops', 'superuser'],
  },
  // P2 Widgets (5)
  {
    id: 'scanner-candidate-funnel',
    type: WidgetType.CHART_BAR,
    category: WidgetCategory.VULNERABILITY_SCANNER,
    name: 'Candidate Filter Funnel',
    description: 'Funnel: Files > Code Units > Candidates > Findings',
    dataSource: 'scanner/metrics/candidate-funnel',
    component: 'CandidateFunnelWidget',
    defaultRefreshSeconds: 300,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 2,
    minHeight: 3,
    defaultWidth: 4,
    defaultHeight: 3,
    defaultColor: 'aura',
    requiredRoles: ['security-engineer', 'superuser'],
  },
  {
    id: 'scanner-findings-by-language',
    type: WidgetType.CHART_DONUT,
    category: WidgetCategory.VULNERABILITY_SCANNER,
    name: 'Findings by Language',
    description: 'Distribution of findings across programming languages',
    dataSource: 'scanner/metrics/findings-by-language',
    component: 'FindingsByLanguageWidget',
    defaultRefreshSeconds: 300,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 2,
    minHeight: 2,
    defaultWidth: 4,
    defaultHeight: 3,
    defaultColor: 'aura',
    requiredRoles: ['security-engineer', 'superuser'],
  },
  {
    id: 'scanner-verification-status',
    type: WidgetType.CHART_DONUT,
    category: WidgetCategory.VULNERABILITY_SCANNER,
    name: 'Verification Status Distribution',
    description: 'Distribution of finding verification outcomes',
    dataSource: 'scanner/metrics/verification-status',
    component: 'VerificationStatusWidget',
    defaultRefreshSeconds: 300,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 2,
    minHeight: 2,
    defaultWidth: 4,
    defaultHeight: 3,
    defaultColor: 'olive',
    requiredRoles: ['security-engineer', 'superuser'],
  },
  {
    id: 'scanner-cleanup-activity',
    type: WidgetType.CHART_BAR,
    category: WidgetCategory.VULNERABILITY_SCANNER,
    name: 'Cleanup Activity',
    description: 'Post-scan cleanup operations over time',
    dataSource: 'scanner/metrics/cleanup-activity',
    component: 'CleanupActivityWidget',
    defaultRefreshSeconds: 300,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 2,
    minHeight: 2,
    defaultWidth: 4,
    defaultHeight: 3,
    defaultColor: 'surface',
    requiredRoles: ['devops', 'superuser'],
  },
  {
    id: 'scanner-depth-distribution',
    type: WidgetType.CHART_DONUT,
    category: WidgetCategory.VULNERABILITY_SCANNER,
    name: 'Scan Depth Distribution',
    description: 'Distribution of scans by configured depth level',
    dataSource: 'scanner/metrics/scan-depth-distribution',
    component: 'ScanDepthDistributionWidget',
    defaultRefreshSeconds: 300,
    supportsSparkline: false,
    supportsTrend: false,
    minWidth: 2,
    minHeight: 2,
    defaultWidth: 4,
    defaultHeight: 3,
    defaultColor: 'aura',
    requiredRoles: ['devops', 'superuser'],
  },
];

// Category labels for display
export const CATEGORY_LABELS = {
  [WidgetCategory.SECURITY]: 'Security',
  [WidgetCategory.OPERATIONS]: 'Operations',
  [WidgetCategory.ANALYTICS]: 'Analytics',
  [WidgetCategory.COMPLIANCE]: 'Compliance',
  [WidgetCategory.COST]: 'Cost',
  [WidgetCategory.THREAT_INTELLIGENCE]: 'Threat Intelligence',
  [WidgetCategory.SUPPLY_CHAIN]: 'Supply Chain Security',
  [WidgetCategory.RUNTIME_SECURITY]: 'Runtime Security',
  [WidgetCategory.AIRGAP_EDGE]: 'Air-Gapped & Edge',
  [WidgetCategory.AI_SECURITY]: 'AI Security',
  [WidgetCategory.VULNERABILITY_SCANNER]: 'Vulnerability Scanner',
};

// Get widgets by category
export function getWidgetsByCategory(category) {
  return WIDGET_CATALOG.filter((w) => w.category === category);
}

// Get widget by ID
export function getWidgetById(id) {
  return WIDGET_CATALOG.find((w) => w.id === id);
}

// Get all categories with their widgets
export function getCategorizedWidgets() {
  return Object.values(WidgetCategory).map((category) => ({
    category,
    label: CATEGORY_LABELS[category],
    widgets: getWidgetsByCategory(category),
  }));
}

// Role-based default dashboard configurations
export const ROLE_DEFAULT_CONFIGS = {
  [UserRole.SECURITY_ENGINEER]: {
    name: 'Security Overview',
    description: 'Security-focused dashboard for vulnerability management and scanning',
    widgets: [
      // Row 0: Scanner approval + active scans + true positive rate + alarm status
      { id: 'scanner-findings-requiring-approval', x: 0, y: 0, w: 3, h: 2 },
      { id: 'scanner-active-scans', x: 3, y: 0, w: 3, h: 3 },
      { id: 'scanner-true-positive-rate', x: 6, y: 0, w: 3, h: 2 },
      { id: 'scanner-alarm-status', x: 9, y: 0, w: 3, h: 3 },
      // Row 1: Findings by severity + critical findings trend
      { id: 'scanner-findings-by-severity', x: 0, y: 3, w: 6, h: 3 },
      { id: 'scanner-critical-findings-trend', x: 6, y: 3, w: 6, h: 3 },
      // Row 2: Recent scan activity + findings by CWE
      { id: 'scanner-recent-activity', x: 0, y: 6, w: 6, h: 3 },
      { id: 'scanner-findings-by-cwe', x: 6, y: 6, w: 6, h: 3 },
    ],
  },
  [UserRole.DEVOPS]: {
    name: 'Operations Overview',
    description: 'DevOps-focused dashboard with scanner operations',
    widgets: [
      // Row 0: Scanner ops
      { id: 'scanner-active-scans', x: 0, y: 0, w: 3, h: 3 },
      { id: 'scanner-concurrent-utilization', x: 3, y: 0, w: 3, h: 2 },
      { id: 'scanner-llm-token-spend', x: 6, y: 0, w: 3, h: 3 },
      { id: 'scanner-alarm-status', x: 9, y: 0, w: 3, h: 3 },
      // Row 1: Duration analysis
      { id: 'scanner-stage-duration', x: 0, y: 3, w: 6, h: 3 },
      { id: 'scanner-duration-trend', x: 6, y: 3, w: 6, h: 3 },
    ],
  },
  [UserRole.COMPLIANCE_OFFICER]: {
    name: 'Compliance Overview',
    description: 'Compliance-focused dashboard for governance and risk',
    widgets: [
      { id: 'compliance-progress', x: 0, y: 0, w: 4, h: 2 },
      { id: 'risk-posture-score', x: 4, y: 0, w: 4, h: 2 },
      { id: 'palantir-insider-risk', x: 8, y: 0, w: 3, h: 2 },
      { id: 'palantir-compliance-drift', x: 0, y: 2, w: 4, h: 4 },
      { id: 'palantir-cve-prioritization', x: 4, y: 2, w: 4, h: 4 },
      { id: 'key-incidents', x: 0, y: 6, w: 12, h: 3 },
    ],
  },
  [UserRole.ENGINEERING_MANAGER]: {
    name: 'Engineering Overview',
    description: 'Dashboard for engineering leadership',
    widgets: [
      { id: 'code-quality-score', x: 0, y: 0, w: 3, h: 2 },
      { id: 'deployment-velocity', x: 3, y: 0, w: 3, h: 2 },
      { id: 'open-vulnerabilities', x: 6, y: 0, w: 3, h: 2 },
      { id: 'pending-approvals', x: 9, y: 0, w: 3, h: 2 },
      { id: 'test-coverage-trend', x: 0, y: 2, w: 6, h: 3 },
      { id: 'pr-velocity-by-team', x: 6, y: 2, w: 6, h: 3 },
    ],
  },
  [UserRole.EXECUTIVE]: {
    name: 'Executive Summary',
    description: 'High-level overview with vulnerability risk metrics',
    widgets: [
      { id: 'risk-posture-score', x: 0, y: 0, w: 3, h: 2 },
      { id: 'scanner-critical-findings-trend', x: 3, y: 0, w: 6, h: 3 },
      { id: 'scanner-llm-token-spend', x: 9, y: 0, w: 3, h: 3 },
      { id: 'key-incidents', x: 0, y: 3, w: 12, h: 3 },
    ],
  },
  [UserRole.SUPERUSER]: {
    name: 'SuperUser Dashboard',
    description: 'Full access dashboard with all widget types',
    widgets: [
      { id: 'risk-posture-score', x: 0, y: 0, w: 4, h: 2 },
      { id: 'compliance-progress', x: 4, y: 0, w: 4, h: 2 },
      { id: 'monthly-cost', x: 8, y: 0, w: 4, h: 2 },
      { id: 'key-incidents', x: 0, y: 2, w: 12, h: 3 },
    ],
  },
};

export default {
  WidgetType,
  WidgetCategory,
  UserRole,
  WIDGET_CATALOG,
  CATEGORY_LABELS,
  ROLE_DEFAULT_CONFIGS,
  getWidgetsByCategory,
  getWidgetById,
  getCategorizedWidgets,
};
