#!/usr/bin/env python3
"""
Project Aura - AI Attribution Stripping Commit-msg Hook

Automatically removes AI attribution from commit messages to comply
with Project Aura documentation standards (see CLAUDE.md).

Patterns removed:
    - Co-Authored-By: Claude <noreply@anthropic.com>
    - Co-Authored-By: Claude Opus 4.5 <noreply@anthropic.com>
    - Generated with [Claude Code](https://claude.com/claude-code)
    - Robot emoji lines referencing Claude Code

Usage:
    python -m scripts.security_hooks.commit_msg_hook <commit-msg-file>

Exit codes:
    0 - Success (message cleaned or already clean)

Author: Project Aura Team
Created: 2025-01-04
"""

import re
import sys
from pathlib import Path


# ANSI color codes for terminal output
class Colors:
    YELLOW = "\033[93m"
    GREEN = "\033[92m"
    BLUE = "\033[94m"
    BOLD = "\033[1m"
    RESET = "\033[0m"


# Patterns to strip from commit messages
AI_ATTRIBUTION_PATTERNS = [
    # Co-authored-by lines for Claude (any variation)
    re.compile(
        r"^\s*Co-Authored-By:\s*Claude.*<.*@anthropic\.com>.*$",
        re.IGNORECASE | re.MULTILINE,
    ),
    # Generated with Claude Code line (with or without emoji)
    re.compile(
        r"^\s*🤖?\s*Generated with \[Claude Code\].*$",
        re.MULTILINE,
    ),
    # Plain text version without markdown
    re.compile(
        r"^\s*Generated with Claude Code.*$",
        re.IGNORECASE | re.MULTILINE,
    ),
    # Any line mentioning Claude assistance
    re.compile(
        r"^\s*.*Generated by Claude.*$",
        re.IGNORECASE | re.MULTILINE,
    ),
    # Robot emoji followed by Claude reference
    re.compile(
        r"^\s*🤖.*[Cc]laude.*$",
        re.MULTILINE,
    ),
]


def print_banner():
    """Print hook banner."""
    print(
        f"\n{Colors.BLUE}{Colors.BOLD}=== Aura AI Attribution Stripper ==={Colors.RESET}\n"
    )


def strip_ai_attribution(message: str) -> tuple[str, int]:
    """
    Remove AI attribution patterns from commit message.

    Args:
        message: Original commit message

    Returns:
        Tuple of (cleaned message, number of patterns removed)
    """
    patterns_removed = 0
    cleaned = message

    for pattern in AI_ATTRIBUTION_PATTERNS:
        matches = pattern.findall(cleaned)
        if matches:
            patterns_removed += len(matches)
            cleaned = pattern.sub("", cleaned)

    # Clean up excessive blank lines (more than 2 consecutive)
    cleaned = re.sub(r"\n{3,}", "\n\n", cleaned)

    # Remove trailing whitespace and ensure single newline at end
    cleaned = cleaned.rstrip() + "\n"

    return cleaned, patterns_removed


def main():
    """Main hook entry point."""
    print_banner()

    # Get commit message file from command line
    if len(sys.argv) < 2:
        print(
            f"  {Colors.YELLOW}Warning: No commit message file provided.{Colors.RESET}"
        )
        return 0

    commit_msg_file = Path(sys.argv[1])

    if not commit_msg_file.exists():
        print(f"  {Colors.YELLOW}Warning: Commit message file not found.{Colors.RESET}")
        return 0

    # Read the commit message
    try:
        original_message = commit_msg_file.read_text(encoding="utf-8")
    except Exception as e:
        print(
            f"  {Colors.YELLOW}Warning: Could not read commit message: {e}{Colors.RESET}"
        )
        return 0

    # Strip AI attribution
    cleaned_message, patterns_removed = strip_ai_attribution(original_message)

    if patterns_removed > 0:
        # Write the cleaned message back
        try:
            commit_msg_file.write_text(cleaned_message, encoding="utf-8")
            print(
                f"  {Colors.GREEN}Removed {patterns_removed} AI attribution pattern(s).{Colors.RESET}"
            )
        except Exception as e:
            print(
                f"  {Colors.YELLOW}Warning: Could not write cleaned message: {e}{Colors.RESET}"
            )
            return 0
    else:
        print(f"  {Colors.GREEN}No AI attribution found.{Colors.RESET}")

    print()
    return 0


if __name__ == "__main__":
    sys.exit(main())
