"""
Security Agent Services - AWS Security Agent Parity

This module provides comprehensive security capabilities replicating
AWS Security Agent functionality:

- PR Security Scanner: Vulnerability detection, secret scanning, SCA, IaC security
- Dynamic Attack Planner: MITRE ATT&CK integration, attack path discovery, threat modeling
- Org Standards Validator: Custom standards enforcement, compliance mapping
- Security Agent Orchestrator: Unified security workflow automation

Reference: ADR-030 Section 5.2 Security Agent Components
"""

from .dynamic_attack_planner import (
    Asset,
    AssetType,
    AttackPath,
    AttackPhase,
    AttackScenario,
    AttackSimulation,
    AttackStatus,
    AttackStep,
    AttackSurface,
    AttackVector,
    DynamicAttackPlanner,
    ExploitDifficulty,
    MITRETechnique,
    RemediationPlan,
    RemediationStep,
    RiskLevel,
    ThreatActor,
    ThreatModel,
    Vulnerability,
)
from .graphrag_security_service import (
    AnomalyScore,
    EntitySignature,
    GraphRAGSecurityService,
    IntegrityAuditResult,
    SignatureAlgorithm,
    ValidationFinding,
    ValidationSeverity,
    create_graphrag_security_service,
)
from .org_standards_validator import (
    ComplianceMapping,
    EnforcementLevel,
    ExemptionRequest,
    OrgStandardsValidator,
    StandardCategory,
    StandardRule,
    StandardsPolicy,
    StandardViolation,
    ValidationReport,
    ValidationResult,
    ValidationStatus,
    ViolationSeverity,
)
from .pr_security_scanner import (
    CodeLocation,
    CVSSScore,
    CWEReference,
    DependencyInfo,
    DependencyVulnerability,
    FindingCategory,
    IaCFinding,
    LicenseIssue,
    PRMetadata,
    PRSecurityScanner,
    RegexSecurityRule,
    Remediation,
    RemediationStatus,
    ScanConfiguration,
    ScanResult,
    ScanStatus,
    ScanSummary,
    SecretFinding,
    SecurityFinding,
    SecurityRule,
    SeverityLevel,
)
from .security_agent_orchestrator import (
    ActionType,
    CorrelatedFinding,
    OverallRiskLevel,
    PRSecurityReview,
    SecurityAction,
    SecurityAgentOrchestrator,
    SecurityAssessment,
    SecurityInsight,
    SecurityWorkflowType,
    WorkflowResult,
    WorkflowStatus,
)

__all__ = [
    # PR Security Scanner
    "PRSecurityScanner",
    "PRMetadata",
    "ScanConfiguration",
    "ScanResult",
    "ScanSummary",
    "SecurityFinding",
    "SecretFinding",
    "DependencyInfo",
    "DependencyVulnerability",
    "IaCFinding",
    "LicenseIssue",
    "CodeLocation",
    "CWEReference",
    "CVSSScore",
    "Remediation",
    "SeverityLevel",
    "FindingCategory",
    "ScanStatus",
    "RemediationStatus",
    "SecurityRule",
    "RegexSecurityRule",
    # Dynamic Attack Planner
    "DynamicAttackPlanner",
    "Asset",
    "AssetType",
    "Vulnerability",
    "AttackVector",
    "AttackPath",
    "AttackStep",
    "AttackSurface",
    "ThreatModel",
    "ThreatActor",
    "AttackScenario",
    "AttackSimulation",
    "RemediationPlan",
    "RemediationStep",
    "MITRETechnique",
    "AttackPhase",
    "RiskLevel",
    "ExploitDifficulty",
    "AttackStatus",
    # Org Standards Validator
    "OrgStandardsValidator",
    "StandardRule",
    "StandardsPolicy",
    "StandardViolation",
    "ValidationReport",
    "ValidationResult",
    "ComplianceMapping",
    "ExemptionRequest",
    "StandardCategory",
    "ViolationSeverity",
    "ValidationStatus",
    "EnforcementLevel",
    # Security Agent Orchestrator
    "SecurityAgentOrchestrator",
    "PRSecurityReview",
    "SecurityAssessment",
    "SecurityAction",
    "SecurityInsight",
    "CorrelatedFinding",
    "WorkflowResult",
    "SecurityWorkflowType",
    "WorkflowStatus",
    "OverallRiskLevel",
    "ActionType",
    # GraphRAG Security Service
    "GraphRAGSecurityService",
    "create_graphrag_security_service",
    "EntitySignature",
    "AnomalyScore",
    "ValidationFinding",
    "ValidationSeverity",
    "SignatureAlgorithm",
    "IntegrityAuditResult",
]
