{{- if and .Values.frontend.enabled .Values.frontend.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "aura.fullname" . }}-frontend
  labels:
    {{- include "aura.componentLabels" (dict "component" "frontend" "context" .) | nindent 4 }}
spec:
  {{- if .Values.frontend.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.frontend.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.frontend.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.frontend.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "aura.componentSelectorLabels" (dict "component" "frontend" "context" .) | nindent 6 }}
{{- end }}
