"""Data contracts for the object-code verification track.

DO-178C 6.4.4.2c requires that, for DAL A software, the verifier
demonstrate that the *object code* generated by the compiler matches
the *source code* that was reviewed, tested, and structurally
covered. Pragmatically this means:

1. Compile source -> object with the same toolchain used in
   production.
2. Disassemble / parse the object's symbol and CFG structure.
3. Establish a traceable mapping (source-line -> object-instruction)
   that demonstrates no compiler-introduced code paths beyond what
   the source review covered.

This module ships only the data contracts and the Port shape. The
real implementation lives in follow-on PRs (#210 Phase 2 = gcc +
objdump; #210 Phase 3 = embedded-target harness).
"""

from __future__ import annotations

import enum
from dataclasses import dataclass, field
from datetime import datetime, timezone


class ObjectCodeVerifierStatus(enum.Enum):
    """Outcome of an object-code verification pass."""

    MATCHED = "matched"
    """Object code traceable to reviewed source; verifier passed."""

    MISMATCHED = "mismatched"
    """Object code contains paths not present in source; verifier failed."""

    NOT_IMPLEMENTED = "not_implemented"
    """Verifier is configured but the underlying toolchain is a stub.

    The DAL gate treats this as ``MISMATCHED`` for safety -- a DAL A
    profile cannot certify COMPLETED while the verifier is a stub.
    """

    TOOLCHAIN_UNAVAILABLE = "toolchain_unavailable"
    """Required compiler / disassembler is not installed.

    Distinct from ``NOT_IMPLEMENTED``: the verifier *is* real but the
    environment is missing the tools. Same gate behaviour (block
    COMPLETED at DAL A) but a different operator action (install
    toolchain vs ship Phase 2).
    """


@dataclass(frozen=True)
class ObjectCodeVerdict:
    """Result of one object-code verification pass."""

    status: ObjectCodeVerifierStatus
    verifier_id: str  # which verifier produced this verdict
    target_triple: str = ""  # e.g. "x86_64-linux-gnu", "armv7-eabi"
    toolchain: str = ""  # e.g. "gcc-13.2.0", "arm-none-eabi-gcc-12"
    source_symbol_count: int = 0
    object_symbol_count: int = 0
    unexpected_symbols: tuple[str, ...] = ()  # in object but not in source
    missing_symbols: tuple[str, ...] = ()  # in source but not in object
    rationale: str = ""
    latency_ms: float = 0.0
    computed_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    @property
    def passed(self) -> bool:
        return self.status == ObjectCodeVerifierStatus.MATCHED

    def to_audit_dict(self) -> dict:
        return {
            "status": self.status.value,
            "verifier_id": self.verifier_id,
            "target_triple": self.target_triple,
            "toolchain": self.toolchain,
            "source_symbol_count": self.source_symbol_count,
            "object_symbol_count": self.object_symbol_count,
            "unexpected_symbol_count": len(self.unexpected_symbols),
            "missing_symbol_count": len(self.missing_symbols),
            "rationale": self.rationale,
            "latency_ms": self.latency_ms,
            "computed_at": self.computed_at.isoformat(),
        }
