{{- if and .Values.license.key (not .Values.license.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aura.fullname" . }}-license
  labels:
    {{- include "aura.labels" . | nindent 4 }}
type: Opaque
data:
  license-key: {{ .Values.license.key | b64enc | quote }}
{{- end }}
