"""Widget Catalog for Dashboard Customization.

Defines all available widgets with their metadata, data sources,
and display configurations per ADR-064.
"""

from __future__ import annotations

from .models import WidgetCatalog, WidgetCategory, WidgetDefinition, WidgetType


def get_widget_catalog() -> WidgetCatalog:
    """Get the complete widget catalog with all available widgets.

    Returns:
        WidgetCatalog with all widget definitions and categories
    """
    widgets = [
        # =====================================================================
        # Security Widgets
        # =====================================================================
        WidgetDefinition(
            widget_type=WidgetType.METRIC,
            category=WidgetCategory.SECURITY,
            name="Open Vulnerabilities",
            description="Count of currently open security vulnerabilities",
            default_data_source="security/vulnerabilities/open",
            default_refresh_seconds=60,
            supports_sparkline=True,
            supports_trend=True,
            min_width=1,
            min_height=2,
            default_width=3,
            default_height=2,
        ),
        WidgetDefinition(
            widget_type=WidgetType.METRIC,
            category=WidgetCategory.SECURITY,
            name="Mean Time to Remediate",
            description="Average time to fix vulnerabilities (in hours)",
            default_data_source="security/metrics/mttr",
            default_refresh_seconds=300,
            supports_sparkline=True,
            supports_trend=True,
            min_width=1,
            min_height=2,
            default_width=3,
            default_height=2,
        ),
        WidgetDefinition(
            widget_type=WidgetType.CHART_LINE,
            category=WidgetCategory.SECURITY,
            name="CVE Trend",
            description="30-day trend of CVE discoveries and patches",
            default_data_source="security/cve/trend",
            default_refresh_seconds=300,
            supports_sparkline=False,
            supports_trend=False,
            min_width=3,
            min_height=2,
            default_width=6,
            default_height=3,
        ),
        WidgetDefinition(
            widget_type=WidgetType.ACTIVITY_FEED,
            category=WidgetCategory.SECURITY,
            name="Recent Security Alerts",
            description="Latest security alerts and notifications",
            default_data_source="security/alerts/recent",
            default_refresh_seconds=30,
            supports_sparkline=False,
            supports_trend=False,
            min_width=3,
            min_height=3,
            default_width=6,
            default_height=3,
        ),
        # =====================================================================
        # Runtime Security Widgets (ADR-083)
        # =====================================================================
        WidgetDefinition(
            widget_type=WidgetType.GAUGE,
            category=WidgetCategory.SECURITY,
            name="Red Team Block Rate",
            description="Percentage of automated adversarial attacks blocked by security controls",
            default_data_source="runtime-security/red-team/block-rate",
            default_refresh_seconds=300,
            supports_sparkline=False,
            supports_trend=False,
            min_width=2,
            min_height=2,
            default_width=3,
            default_height=2,
        ),
        WidgetDefinition(
            widget_type=WidgetType.METRIC,
            category=WidgetCategory.SECURITY,
            name="Shadow Agents Detected",
            description="Unregistered agents discovered via traffic analysis",
            default_data_source="runtime-security/discovery/shadow-agents",
            default_refresh_seconds=60,
            supports_sparkline=True,
            supports_trend=True,
            min_width=1,
            min_height=2,
            default_width=3,
            default_height=2,
        ),
        WidgetDefinition(
            widget_type=WidgetType.ACTIVITY_FEED,
            category=WidgetCategory.SECURITY,
            name="Behavioral Anomalies",
            description="Recent behavioral deviations detected by baseline engine",
            default_data_source="runtime-security/baselines/anomalies",
            default_refresh_seconds=30,
            supports_sparkline=False,
            supports_trend=False,
            min_width=3,
            min_height=3,
            default_width=6,
            default_height=3,
        ),
        WidgetDefinition(
            widget_type=WidgetType.GAUGE,
            category=WidgetCategory.SECURITY,
            name="Correlation Rate",
            description="Percentage of runtime events correlated to source code root causes",
            default_data_source="runtime-security/correlation/rate",
            default_refresh_seconds=300,
            supports_sparkline=False,
            supports_trend=False,
            min_width=2,
            min_height=2,
            default_width=3,
            default_height=2,
        ),
        WidgetDefinition(
            widget_type=WidgetType.CHART_BAR,
            category=WidgetCategory.SECURITY,
            name="Red Team Results by Category",
            description="Attack test outcomes grouped by AURA-ATT&CK category",
            default_data_source="runtime-security/red-team/by-category",
            default_refresh_seconds=300,
            supports_sparkline=False,
            supports_trend=False,
            min_width=3,
            min_height=2,
            default_width=6,
            default_height=3,
        ),
        # =====================================================================
        # Operations Widgets
        # =====================================================================
        WidgetDefinition(
            widget_type=WidgetType.METRIC,
            category=WidgetCategory.OPERATIONS,
            name="Pending Approvals",
            description="Number of items awaiting HITL approval",
            default_data_source="approvals/pending/count",
            default_refresh_seconds=30,
            supports_sparkline=True,
            supports_trend=True,
            min_width=1,
            min_height=2,
            default_width=3,
            default_height=2,
        ),
        WidgetDefinition(
            widget_type=WidgetType.STATUS_GRID,
            category=WidgetCategory.OPERATIONS,
            name="Agent Health Grid",
            description="Health status of all active agents",
            default_data_source="agents/health/grid",
            default_refresh_seconds=30,
            supports_sparkline=False,
            supports_trend=False,
            min_width=3,
            min_height=2,
            default_width=6,
            default_height=3,
        ),
        WidgetDefinition(
            widget_type=WidgetType.GAUGE,
            category=WidgetCategory.OPERATIONS,
            name="Sandbox Utilization",
            description="Current sandbox environment utilization percentage",
            default_data_source="environments/sandbox/utilization",
            default_refresh_seconds=60,
            supports_sparkline=False,
            supports_trend=False,
            min_width=2,
            min_height=2,
            default_width=3,
            default_height=2,
        ),
        WidgetDefinition(
            widget_type=WidgetType.STATUS_GRID,
            category=WidgetCategory.OPERATIONS,
            name="Environment Status",
            description="Status of dev/qa/prod environments",
            default_data_source="environments/status",
            default_refresh_seconds=60,
            supports_sparkline=False,
            supports_trend=False,
            min_width=2,
            min_height=2,
            default_width=3,
            default_height=2,
        ),
        WidgetDefinition(
            widget_type=WidgetType.METRIC,
            category=WidgetCategory.OPERATIONS,
            name="GPU Jobs Queued",
            description="Number of GPU jobs waiting in queue",
            default_data_source="gpu/jobs/queued",
            default_refresh_seconds=30,
            supports_sparkline=True,
            supports_trend=True,
            min_width=1,
            min_height=2,
            default_width=3,
            default_height=2,
        ),
        WidgetDefinition(
            widget_type=WidgetType.METRIC,
            category=WidgetCategory.OPERATIONS,
            name="Deployment Velocity",
            description="Deployments per day (7-day average)",
            default_data_source="deployments/velocity",
            default_refresh_seconds=300,
            supports_sparkline=True,
            supports_trend=True,
            min_width=1,
            min_height=2,
            default_width=3,
            default_height=2,
        ),
        WidgetDefinition(
            widget_type=WidgetType.CHART_LINE,
            category=WidgetCategory.OPERATIONS,
            name="Agent Traffic Volume",
            description="Agent traffic events captured over time (24h trend)",
            default_data_source="runtime-security/interceptor/volume-trend",
            default_refresh_seconds=300,
            supports_sparkline=False,
            supports_trend=False,
            min_width=3,
            min_height=2,
            default_width=6,
            default_height=3,
        ),
        # =====================================================================
        # Analytics Widgets
        # =====================================================================
        WidgetDefinition(
            widget_type=WidgetType.METRIC,
            category=WidgetCategory.ANALYTICS,
            name="Code Quality Score",
            description="Overall code quality score (0-100)",
            default_data_source="analytics/code-quality/score",
            default_refresh_seconds=300,
            supports_sparkline=True,
            supports_trend=True,
            min_width=1,
            min_height=2,
            default_width=3,
            default_height=2,
        ),
        WidgetDefinition(
            widget_type=WidgetType.CHART_LINE,
            category=WidgetCategory.ANALYTICS,
            name="Test Coverage Trend",
            description="Test coverage percentage over time",
            default_data_source="analytics/test-coverage/trend",
            default_refresh_seconds=300,
            supports_sparkline=False,
            supports_trend=False,
            min_width=3,
            min_height=2,
            default_width=6,
            default_height=3,
        ),
        WidgetDefinition(
            widget_type=WidgetType.CHART_BAR,
            category=WidgetCategory.ANALYTICS,
            name="PR Velocity by Team",
            description="Pull request velocity grouped by team",
            default_data_source="analytics/pr/velocity-by-team",
            default_refresh_seconds=300,
            supports_sparkline=False,
            supports_trend=False,
            min_width=3,
            min_height=2,
            default_width=6,
            default_height=3,
        ),
        WidgetDefinition(
            widget_type=WidgetType.CHART_DONUT,
            category=WidgetCategory.ANALYTICS,
            name="Agent Traffic by Type",
            description="Distribution of agent traffic by event type",
            default_data_source="runtime-security/interceptor/by-type",
            default_refresh_seconds=300,
            supports_sparkline=False,
            supports_trend=False,
            min_width=3,
            min_height=2,
            default_width=4,
            default_height=3,
        ),
        # =====================================================================
        # Compliance Widgets
        # =====================================================================
        WidgetDefinition(
            widget_type=WidgetType.PROGRESS,
            category=WidgetCategory.COMPLIANCE,
            name="Compliance Progress",
            description="Overall compliance readiness percentage",
            default_data_source="compliance/progress",
            default_refresh_seconds=300,
            supports_sparkline=False,
            supports_trend=True,
            min_width=2,
            min_height=2,
            default_width=4,
            default_height=2,
        ),
        WidgetDefinition(
            widget_type=WidgetType.GAUGE,
            category=WidgetCategory.COMPLIANCE,
            name="Risk Posture Score",
            description="Composite risk posture score (0-100)",
            default_data_source="security/risk-posture",
            default_refresh_seconds=300,
            supports_sparkline=False,
            supports_trend=False,
            min_width=2,
            min_height=2,
            default_width=4,
            default_height=2,
        ),
        WidgetDefinition(
            widget_type=WidgetType.TABLE,
            category=WidgetCategory.COMPLIANCE,
            name="Key Incidents",
            description="Recent key security incidents",
            default_data_source="incidents/recent",
            default_refresh_seconds=60,
            supports_sparkline=False,
            supports_trend=False,
            min_width=4,
            min_height=3,
            default_width=12,
            default_height=3,
        ),
        # =====================================================================
        # Cost Widgets
        # =====================================================================
        WidgetDefinition(
            widget_type=WidgetType.METRIC,
            category=WidgetCategory.COST,
            name="Monthly Cost",
            description="Current month infrastructure cost",
            default_data_source="cost/monthly-summary",
            default_refresh_seconds=3600,
            supports_sparkline=True,
            supports_trend=True,
            min_width=2,
            min_height=2,
            default_width=4,
            default_height=2,
        ),
        WidgetDefinition(
            widget_type=WidgetType.CHART_LINE,
            category=WidgetCategory.COST,
            name="Cost Trend",
            description="30-day infrastructure cost trend",
            default_data_source="cost/trend",
            default_refresh_seconds=3600,
            supports_sparkline=False,
            supports_trend=False,
            min_width=4,
            min_height=2,
            default_width=6,
            default_height=3,
        ),
        # =====================================================================
        # Vulnerability Scanner Widgets (ADR-084)
        # =====================================================================
        # P0 Widgets
        WidgetDefinition(
            widget_type=WidgetType.CHART_BAR,
            category=WidgetCategory.VULNERABILITY_SCANNER,
            name="Scan Findings by Severity",
            description="Stacked bar chart of findings by severity level",
            default_data_source="scanner/metrics/findings-by-severity",
            default_refresh_seconds=60,
            supports_sparkline=False,
            supports_trend=False,
            min_width=3,
            min_height=2,
            default_width=6,
            default_height=3,
        ),
        WidgetDefinition(
            widget_type=WidgetType.METRIC,
            category=WidgetCategory.VULNERABILITY_SCANNER,
            name="Active Scans",
            description="Count of currently running scans with pipeline stage",
            default_data_source="scanner/metrics/active-scans",
            default_refresh_seconds=15,
            supports_sparkline=False,
            supports_trend=False,
            min_width=1,
            min_height=2,
            default_width=3,
            default_height=3,
        ),
        WidgetDefinition(
            widget_type=WidgetType.PROGRESS,
            category=WidgetCategory.VULNERABILITY_SCANNER,
            name="Scan Pipeline Progress",
            description="7-segment progress bar per active scan",
            default_data_source="scanner/metrics/pipeline-progress",
            default_refresh_seconds=10,
            supports_sparkline=False,
            supports_trend=False,
            min_width=3,
            min_height=2,
            default_width=6,
            default_height=3,
        ),
        WidgetDefinition(
            widget_type=WidgetType.GAUGE,
            category=WidgetCategory.VULNERABILITY_SCANNER,
            name="True Positive Rate",
            description="Percentage of verified findings that are true positives",
            default_data_source="scanner/metrics/true-positive-rate",
            default_refresh_seconds=300,
            supports_sparkline=False,
            supports_trend=False,
            min_width=2,
            min_height=2,
            default_width=3,
            default_height=2,
        ),
        WidgetDefinition(
            widget_type=WidgetType.METRIC,
            category=WidgetCategory.VULNERABILITY_SCANNER,
            name="LLM Token Spend",
            description="Daily and monthly LLM token usage and cost",
            default_data_source="scanner/metrics/llm-token-spend",
            default_refresh_seconds=60,
            supports_sparkline=False,
            supports_trend=True,
            min_width=1,
            min_height=2,
            default_width=3,
            default_height=3,
        ),
        WidgetDefinition(
            widget_type=WidgetType.STATUS_GRID,
            category=WidgetCategory.VULNERABILITY_SCANNER,
            name="Scanner Alarm Status",
            description="Health status of scanner CloudWatch alarms",
            default_data_source="scanner/metrics/alarm-status",
            default_refresh_seconds=30,
            supports_sparkline=False,
            supports_trend=False,
            min_width=2,
            min_height=2,
            default_width=3,
            default_height=3,
        ),
        WidgetDefinition(
            widget_type=WidgetType.ACTIVITY_FEED,
            category=WidgetCategory.VULNERABILITY_SCANNER,
            name="Recent Scan Activity",
            description="Activity feed of recent scan events",
            default_data_source="scanner/metrics/recent-activity",
            default_refresh_seconds=30,
            supports_sparkline=False,
            supports_trend=False,
            min_width=3,
            min_height=3,
            default_width=6,
            default_height=3,
        ),
        WidgetDefinition(
            widget_type=WidgetType.METRIC,
            category=WidgetCategory.VULNERABILITY_SCANNER,
            name="Findings Requiring Approval",
            description="Count of findings awaiting HITL approval",
            default_data_source="scanner/metrics/findings-requiring-approval",
            default_refresh_seconds=30,
            supports_sparkline=False,
            supports_trend=True,
            min_width=1,
            min_height=2,
            default_width=3,
            default_height=2,
        ),
        # P1 Widgets
        WidgetDefinition(
            widget_type=WidgetType.CHART_LINE,
            category=WidgetCategory.VULNERABILITY_SCANNER,
            name="Scan Duration Trend",
            description="Time series of scan duration with percentiles",
            default_data_source="scanner/metrics/scan-duration-trend",
            default_refresh_seconds=300,
            supports_sparkline=False,
            supports_trend=False,
            min_width=3,
            min_height=2,
            default_width=6,
            default_height=3,
        ),
        WidgetDefinition(
            widget_type=WidgetType.CHART_BAR,
            category=WidgetCategory.VULNERABILITY_SCANNER,
            name="Stage Duration Waterfall",
            description="Time breakdown across pipeline stages",
            default_data_source="scanner/metrics/stage-duration",
            default_refresh_seconds=300,
            supports_sparkline=False,
            supports_trend=False,
            min_width=3,
            min_height=2,
            default_width=6,
            default_height=3,
        ),
        WidgetDefinition(
            widget_type=WidgetType.CHART_BAR,
            category=WidgetCategory.VULNERABILITY_SCANNER,
            name="Findings by CWE",
            description="Horizontal bar chart of findings by CWE category",
            default_data_source="scanner/metrics/findings-by-cwe",
            default_refresh_seconds=300,
            supports_sparkline=False,
            supports_trend=False,
            min_width=3,
            min_height=2,
            default_width=6,
            default_height=3,
        ),
        WidgetDefinition(
            widget_type=WidgetType.CHART_LINE,
            category=WidgetCategory.VULNERABILITY_SCANNER,
            name="LLM Latency",
            description="P50/P95/P99 LLM response latency percentiles",
            default_data_source="scanner/metrics/llm-latency",
            default_refresh_seconds=30,
            supports_sparkline=False,
            supports_trend=False,
            min_width=3,
            min_height=2,
            default_width=6,
            default_height=3,
        ),
        WidgetDefinition(
            widget_type=WidgetType.GAUGE,
            category=WidgetCategory.VULNERABILITY_SCANNER,
            name="Concurrent Scan Utilization",
            description="Active vs max concurrent scan capacity",
            default_data_source="scanner/metrics/concurrent-utilization",
            default_refresh_seconds=15,
            supports_sparkline=False,
            supports_trend=False,
            min_width=2,
            min_height=2,
            default_width=3,
            default_height=2,
        ),
        WidgetDefinition(
            widget_type=WidgetType.CHART_LINE,
            category=WidgetCategory.VULNERABILITY_SCANNER,
            name="Critical Findings Trend 30d",
            description="30-day trend of critical findings per day",
            default_data_source="scanner/metrics/critical-findings-trend",
            default_refresh_seconds=300,
            supports_sparkline=False,
            supports_trend=False,
            min_width=3,
            min_height=2,
            default_width=6,
            default_height=3,
        ),
        WidgetDefinition(
            widget_type=WidgetType.METRIC,
            category=WidgetCategory.VULNERABILITY_SCANNER,
            name="Scan Queue Depth",
            description="Number of scans waiting in queue",
            default_data_source="scanner/metrics/scan-queue-depth",
            default_refresh_seconds=15,
            supports_sparkline=False,
            supports_trend=True,
            min_width=1,
            min_height=2,
            default_width=3,
            default_height=2,
        ),
        # P2 Widgets
        WidgetDefinition(
            widget_type=WidgetType.CHART_BAR,
            category=WidgetCategory.VULNERABILITY_SCANNER,
            name="Candidate Filter Funnel",
            description="Funnel: Files > Code Units > Candidates > Findings",
            default_data_source="scanner/metrics/candidate-funnel",
            default_refresh_seconds=300,
            supports_sparkline=False,
            supports_trend=False,
            min_width=2,
            min_height=3,
            default_width=4,
            default_height=3,
        ),
        WidgetDefinition(
            widget_type=WidgetType.CHART_DONUT,
            category=WidgetCategory.VULNERABILITY_SCANNER,
            name="Findings by Language",
            description="Distribution of findings across programming languages",
            default_data_source="scanner/metrics/findings-by-language",
            default_refresh_seconds=300,
            supports_sparkline=False,
            supports_trend=False,
            min_width=2,
            min_height=2,
            default_width=4,
            default_height=3,
        ),
        WidgetDefinition(
            widget_type=WidgetType.CHART_DONUT,
            category=WidgetCategory.VULNERABILITY_SCANNER,
            name="Verification Status Distribution",
            description="Distribution of finding verification outcomes",
            default_data_source="scanner/metrics/verification-status",
            default_refresh_seconds=300,
            supports_sparkline=False,
            supports_trend=False,
            min_width=2,
            min_height=2,
            default_width=4,
            default_height=3,
        ),
        WidgetDefinition(
            widget_type=WidgetType.CHART_BAR,
            category=WidgetCategory.VULNERABILITY_SCANNER,
            name="Cleanup Activity",
            description="Post-scan cleanup operations over time",
            default_data_source="scanner/metrics/cleanup-activity",
            default_refresh_seconds=300,
            supports_sparkline=False,
            supports_trend=False,
            min_width=2,
            min_height=2,
            default_width=4,
            default_height=3,
        ),
        WidgetDefinition(
            widget_type=WidgetType.CHART_DONUT,
            category=WidgetCategory.VULNERABILITY_SCANNER,
            name="Scan Depth Distribution",
            description="Distribution of scans by configured depth level",
            default_data_source="scanner/metrics/scan-depth-distribution",
            default_refresh_seconds=300,
            supports_sparkline=False,
            supports_trend=False,
            min_width=2,
            min_height=2,
            default_width=4,
            default_height=3,
        ),
    ]

    return WidgetCatalog(
        widgets=widgets,
        categories=list(WidgetCategory),
    )


# Singleton catalog instance
_catalog: WidgetCatalog | None = None


def get_catalog() -> WidgetCatalog:
    """Get cached widget catalog instance.

    Returns:
        Cached WidgetCatalog
    """
    global _catalog
    if _catalog is None:
        _catalog = get_widget_catalog()
    return _catalog


def get_widgets_by_category(category: WidgetCategory) -> list[WidgetDefinition]:
    """Get all widgets in a specific category.

    Args:
        category: Widget category to filter by

    Returns:
        List of WidgetDefinitions in the category
    """
    catalog = get_catalog()
    return [w for w in catalog.widgets if w.category == category]


def get_widget_by_type(widget_type: WidgetType) -> WidgetDefinition | None:
    """Get widget definition by type.

    Args:
        widget_type: Widget type to find

    Returns:
        WidgetDefinition or None if not found
    """
    catalog = get_catalog()
    for widget in catalog.widgets:
        if widget.widget_type == widget_type:
            return widget
    return None
