{{- if and (include "aura.isSelfHosted" .) .Values.databases.graph.neo4j.enabled }}
{{- if not .Values.databases.graph.neo4j.existingPasswordSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aura.fullname" . }}-neo4j
  labels:
    {{- include "aura.componentLabels" (dict "component" "neo4j" "context" .) | nindent 4 }}
type: Opaque
data:
  {{- if .Values.databases.graph.neo4j.password }}
  neo4j-password: {{ printf "neo4j/%s" .Values.databases.graph.neo4j.password | b64enc | quote }}
  {{- else }}
  neo4j-password: {{ printf "neo4j/%s" (randAlphaNum 24) | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
