"""RuntimeIncidentAgent for Code-Aware Incident Response.

This agent autonomously investigates runtime incidents by correlating
observability data with code intelligence from Neptune graph and OpenSearch.

Part of ADR-025: RuntimeIncidentAgent Architecture
Key Differentiators vs AWS DevOps Agent:
- Maps exceptions to Neptune code graph entities
- Searches OpenSearch for recent code changes
- Correlates incidents with deployment history
- Generates LLM-powered RCA with code context
- GovCloud compatible

Created: 2025-12-06
"""

import json
import logging
import os
import re
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from enum import Enum
from typing import Any, Optional, cast

import boto3

logger = logging.getLogger(__name__)


class IncidentSource(Enum):
    """Source systems that can trigger incident investigations."""

    CLOUDWATCH = "aws.cloudwatch"
    PAGERDUTY = "pagerduty"
    DATADOG = "datadog"
    CUSTOM = "custom"


class IncidentSeverity(Enum):
    """Incident severity levels."""

    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


@dataclass
class IncidentContext:
    """Parsed incident context from event source."""

    alert_name: str
    affected_service: str
    timestamp: str
    error_message: str
    stack_trace: Optional[str] = None
    metric_name: Optional[str] = None
    severity: IncidentSeverity = IncidentSeverity.MEDIUM
    source: IncidentSource = IncidentSource.CUSTOM
    raw_event: dict[str, Any] = field(default_factory=dict)


@dataclass
class DeploymentEvent:
    """Deployment event from deployment correlation table."""

    deployment_id: str
    timestamp: str
    application_name: str
    commit_sha: str
    commit_message: str
    argocd_sync_status: str
    rollout_status: str
    image_tag: str
    deployed_by: str
    source: str


@dataclass
class CodeEntity:
    """Code entity from Neptune graph."""

    entity_id: str
    entity_type: str  # function, class, module
    name: str
    file_path: str
    line_number: Optional[int] = None
    namespace: Optional[str] = None
    dependencies: list[str] = field(default_factory=list)


@dataclass
class GitCommit:
    """Git commit from OpenSearch."""

    sha: str
    message: str
    author: str
    timestamp: str
    file_path: str
    changes_summary: Optional[str] = None


@dataclass
class RCAHypothesis:
    """Root cause analysis hypothesis generated by LLM."""

    hypothesis: str
    confidence: int  # 0-100
    evidence: list[str] = field(default_factory=list)
    alternatives: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary."""
        return {
            "hypothesis": self.hypothesis,
            "confidence": self.confidence,
            "evidence": self.evidence,
            "alternatives": self.alternatives,
        }


@dataclass
class InvestigationResult:
    """Complete investigation result for HITL approval."""

    incident_id: str
    timestamp: str
    source: str
    alert_name: str
    affected_service: str
    rca_hypothesis: str
    confidence_score: int
    deployment_correlation: list[dict[str, Any]]
    code_entities: list[dict[str, Any]]
    git_commits: list[dict[str, Any]]
    mitigation_plan: str
    hitl_status: str = "pending"

    def to_dynamodb_item(self) -> dict[str, Any]:
        """Convert to DynamoDB item format."""
        # Calculate TTL (90 days for dev, 365 for prod)
        environment = os.getenv("ENVIRONMENT", "dev")
        ttl_days = 365 if environment == "prod" else 90
        ttl_timestamp = int(
            (datetime.now(timezone.utc) + timedelta(days=ttl_days)).timestamp()
        )

        return {
            "incident_id": self.incident_id,
            "timestamp": self.timestamp,
            "source": self.source,
            "alert_name": self.alert_name,
            "affected_service": self.affected_service,
            "rca_hypothesis": self.rca_hypothesis,
            "confidence_score": self.confidence_score,
            "deployment_correlation": self.deployment_correlation,
            "code_entities": self.code_entities,
            "git_commits": self.git_commits,
            "mitigation_plan": self.mitigation_plan,
            "hitl_status": self.hitl_status,
            "ttl": ttl_timestamp,
        }


class RuntimeIncidentAgent:
    """
    Autonomous agent for runtime incident investigation with code-aware RCA.

    Unique capabilities vs AWS DevOps Agent:
    - Correlates runtime metrics with Neptune code graph
    - Searches OpenSearch for recent code changes
    - Links incidents to deployment events
    - Generates RCA hypotheses with confidence scores
    - Proposes mitigations with rollback plans
    """

    def __init__(
        self,
        llm_client: Optional[Any] = None,
        context_service: Optional[Any] = None,
        mcp_adapters: Optional[Any] = None,
    ):
        """
        Initialize RuntimeIncidentAgent.

        Args:
            llm_client: BedrockLLMService instance for RCA generation
            context_service: ContextRetrievalService for Neptune/OpenSearch
            mcp_adapters: MCPToolAdapters for observability integration
        """
        self.llm = llm_client
        self.context = context_service
        self.mcp = mcp_adapters

        # AWS clients
        self.dynamodb = boto3.resource("dynamodb")
        self.cloudwatch_logs = boto3.client("logs")

        # DynamoDB tables
        environment = os.getenv("ENVIRONMENT", "dev")
        self.deployments_table = self.dynamodb.Table(f"aura-deployments-{environment}")
        self.investigations_table = self.dynamodb.Table(
            f"aura-incident-investigations-{environment}"
        )

        logger.info(f"RuntimeIncidentAgent initialized for environment: {environment}")

    async def investigate(self, incident_event: dict[str, Any]) -> InvestigationResult:
        """
        Main investigation workflow.

        Args:
            incident_event: EventBridge event containing incident details

        Returns:
            Investigation results with RCA hypothesis, confidence, mitigation plan
        """
        incident_id = incident_event.get(
            "id", f"incident-{datetime.now(timezone.utc).isoformat()}"
        )
        source = incident_event.get("source", "custom")
        detail = incident_event.get("detail", {})

        logger.info(f"Starting investigation for incident: {incident_id}")

        # Step 1: Parse incident context
        incident_context = self._parse_incident_context(source, detail)
        logger.info(
            f"Parsed incident: {incident_context.alert_name} "
            f"affecting {incident_context.affected_service}"
        )

        # Step 2: Query observability platforms
        metrics = await self._query_observability(incident_context)
        logger.info(f"Gathered metrics from {len(metrics)} observability sources")

        # Step 3: Correlate with deployment history
        recent_deployments = await self._query_recent_deployments(
            incident_context.affected_service, incident_context.timestamp
        )
        logger.info(f"Found {len(recent_deployments)} recent deployments")

        # Step 4: Map to code entities in Neptune
        code_entities = await self._correlate_with_code_graph(
            incident_context.error_message, incident_context.stack_trace
        )
        logger.info(f"Correlated with {len(code_entities)} code entities")

        # Step 5: Search for related code changes in OpenSearch
        git_commits = await self._search_recent_changes(
            code_entities, incident_context.timestamp
        )
        logger.info(f"Found {len(git_commits)} related git commits")

        # Step 6: Generate RCA hypothesis using LLM
        rca_result = await self._generate_rca_hypothesis(
            incident_context=incident_context,
            metrics=metrics,
            deployments=recent_deployments,
            code_entities=code_entities,
            git_commits=git_commits,
        )
        logger.info(
            f"Generated RCA hypothesis with {rca_result.confidence}% confidence"
        )

        # Step 7: Propose mitigation plan
        mitigation_plan = await self._generate_mitigation_plan(
            rca_result, recent_deployments
        )
        logger.info("Generated mitigation plan")

        # Step 8: Create investigation result
        investigation = InvestigationResult(
            incident_id=incident_id,
            timestamp=datetime.now(timezone.utc).isoformat(),
            source=source,
            alert_name=incident_context.alert_name,
            affected_service=incident_context.affected_service,
            rca_hypothesis=rca_result.hypothesis,
            confidence_score=rca_result.confidence,
            deployment_correlation=[
                self._deployment_to_dict(d) for d in recent_deployments
            ],
            code_entities=[self._code_entity_to_dict(e) for e in code_entities],
            git_commits=[self._git_commit_to_dict(c) for c in git_commits],
            mitigation_plan=mitigation_plan,
            hitl_status="pending",
        )

        # Step 9: Store investigation results
        self.investigations_table.put_item(Item=investigation.to_dynamodb_item())
        logger.info(f"Investigation {incident_id} stored in DynamoDB")

        return investigation

    def _parse_incident_context(
        self, source: str, detail: dict[str, Any]
    ) -> IncidentContext:
        """Extract standardized incident context from various sources."""
        if source == IncidentSource.CLOUDWATCH.value:
            return self._parse_cloudwatch_alarm(detail)
        elif source == IncidentSource.PAGERDUTY.value:
            return self._parse_pagerduty_incident(detail)
        elif source == IncidentSource.DATADOG.value:
            return self._parse_datadog_alert(detail)
        else:
            # Generic parsing for custom events
            return IncidentContext(
                alert_name=detail.get("alert_name", "Unknown Alert"),
                affected_service=detail.get("service", "unknown"),
                timestamp=detail.get(
                    "timestamp", datetime.now(timezone.utc).isoformat()
                ),
                error_message=detail.get("message", ""),
                stack_trace=detail.get("stack_trace"),
                severity=IncidentSeverity.MEDIUM,
                source=IncidentSource.CUSTOM,
                raw_event=detail,
            )

    def _parse_cloudwatch_alarm(self, detail: dict[str, Any]) -> IncidentContext:
        """Parse CloudWatch alarm event."""
        alarm_name = detail.get("alarmName", "Unknown Alarm")
        service_name = self._extract_service_from_alarm(alarm_name)

        return IncidentContext(
            alert_name=alarm_name,
            affected_service=service_name,
            timestamp=detail.get(
                "stateChangeTime", datetime.now(timezone.utc).isoformat()
            ),
            error_message=detail.get("newStateReason", ""),
            stack_trace=None,
            metric_name=self._extract_metric_from_alarm(detail),
            severity=self._map_alarm_severity(detail.get("newStateValue")),
            source=IncidentSource.CLOUDWATCH,
            raw_event=detail,
        )

    def _parse_pagerduty_incident(self, detail: dict[str, Any]) -> IncidentContext:
        """Parse PagerDuty incident event."""
        incident = detail.get("incident", {})

        return IncidentContext(
            alert_name=incident.get("title", "Unknown Incident"),
            affected_service=incident.get("service", {}).get("name", "unknown"),
            timestamp=incident.get(
                "created_at", datetime.now(timezone.utc).isoformat()
            ),
            error_message=incident.get("body", {}).get("details", ""),
            stack_trace=None,
            severity=self._map_pagerduty_severity(incident.get("urgency")),
            source=IncidentSource.PAGERDUTY,
            raw_event=detail,
        )

    def _parse_datadog_alert(self, detail: dict[str, Any]) -> IncidentContext:
        """Parse Datadog alert event."""
        return IncidentContext(
            alert_name=detail.get("title", "Unknown Alert"),
            affected_service=detail.get("tags", {}).get("service", "unknown"),
            timestamp=detail.get("date", datetime.now(timezone.utc).isoformat()),
            error_message=detail.get("body", ""),
            stack_trace=None,
            severity=self._map_datadog_severity(detail.get("priority")),
            source=IncidentSource.DATADOG,
            raw_event=detail,
        )

    def _extract_service_from_alarm(self, alarm_name: str) -> str:
        """Extract service name from CloudWatch alarm name."""
        # Example: "aura-api-high-cpu-dev" -> "aura-api"
        parts = alarm_name.split("-")
        if len(parts) >= 2:
            return "-".join(parts[:2])
        return "unknown"

    def _extract_metric_from_alarm(self, detail: dict[str, Any]) -> Optional[str]:
        """Extract metric name from CloudWatch alarm configuration."""
        try:
            metrics = detail.get("configuration", {}).get("metrics", [])
            if metrics:
                return cast(
                    str | None,
                    metrics[0].get("metricStat", {}).get("metric", {}).get("name"),
                )
        except (KeyError, IndexError):
            pass
        return None

    def _map_alarm_severity(self, state_value: Optional[str]) -> IncidentSeverity:
        """Map CloudWatch alarm state to incident severity."""
        if state_value == "ALARM":
            return IncidentSeverity.HIGH
        return IncidentSeverity.MEDIUM

    def _map_pagerduty_severity(self, urgency: Optional[str]) -> IncidentSeverity:
        """Map PagerDuty urgency to incident severity."""
        mapping = {
            "high": IncidentSeverity.CRITICAL,
            "low": IncidentSeverity.MEDIUM,
        }
        return mapping.get(urgency or "low", IncidentSeverity.MEDIUM)

    def _map_datadog_severity(self, priority: Optional[str]) -> IncidentSeverity:
        """Map Datadog priority to incident severity."""
        mapping = {
            "P1": IncidentSeverity.CRITICAL,
            "P2": IncidentSeverity.HIGH,
            "P3": IncidentSeverity.MEDIUM,
            "P4": IncidentSeverity.LOW,
            "P5": IncidentSeverity.INFO,
        }
        return mapping.get(priority or "P3", IncidentSeverity.MEDIUM)

    async def _query_observability(
        self, incident_context: IncidentContext
    ) -> dict[str, Any]:
        """Query CloudWatch, Datadog, Prometheus for incident window metrics."""
        incident_time = datetime.fromisoformat(
            incident_context.timestamp.replace("Z", "+00:00")
        )
        start_time = incident_time - timedelta(minutes=30)
        end_time = incident_time + timedelta(minutes=5)

        metrics: dict[str, Any] = {}

        # CloudWatch Logs (errors in incident window)
        cloudwatch_logs = await self._query_cloudwatch_logs(
            log_group=f"/ecs/{incident_context.affected_service}",
            start_time=start_time,
            end_time=end_time,
            filter_pattern="ERROR",
        )
        metrics["cloudwatch_logs"] = cloudwatch_logs

        # Datadog APM traces (if Enterprise mode and MCP adapters available)
        if self.mcp and hasattr(self.mcp, "is_enterprise_mode"):
            if self.mcp.is_enterprise_mode():
                try:
                    datadog_traces = await self.mcp.datadog_query_traces(
                        service=incident_context.affected_service,
                        time_range=(start_time, end_time),
                        error_only=True,
                    )
                    metrics["datadog_traces"] = datadog_traces
                except Exception as e:
                    logger.warning(f"Failed to query Datadog traces: {e}")
                    metrics["datadog_traces"] = []

        # Prometheus metrics (if MCP adapters available)
        if self.mcp and hasattr(self.mcp, "prometheus_query_range"):
            try:
                prometheus_metrics = await self.mcp.prometheus_query_range(
                    query=f'rate(container_cpu_usage_seconds_total{{pod=~"{incident_context.affected_service}.*"}}[5m])',
                    start_time=start_time,
                    end_time=end_time,
                )
                metrics["prometheus_cpu"] = prometheus_metrics
            except Exception as e:
                logger.warning(f"Failed to query Prometheus: {e}")
                metrics["prometheus_cpu"] = {}

        return metrics

    async def _query_cloudwatch_logs(
        self,
        log_group: str,
        start_time: datetime,
        end_time: datetime,
        filter_pattern: str,
    ) -> list[dict[str, Any]]:
        """Query CloudWatch Logs for incident window."""
        try:
            response = self.cloudwatch_logs.filter_log_events(
                logGroupName=log_group,
                startTime=int(start_time.timestamp() * 1000),
                endTime=int(end_time.timestamp() * 1000),
                filterPattern=filter_pattern,
                limit=100,
            )
            return cast(list[dict[str, Any]], response.get("events", []))
        except Exception as e:
            logger.warning(f"Failed to query CloudWatch Logs: {e}")
            return []

    async def _query_recent_deployments(
        self, service_name: str, incident_time: str, lookback_hours: int = 24
    ) -> list[DeploymentEvent]:
        """Query deployment history to find recent changes."""
        incident_dt = datetime.fromisoformat(incident_time.replace("Z", "+00:00"))
        cutoff_time = incident_dt - timedelta(hours=lookback_hours)

        try:
            response = self.deployments_table.query(
                IndexName="by-application",
                KeyConditionExpression="application_name = :app AND #ts > :cutoff",
                ExpressionAttributeNames={"#ts": "timestamp"},
                ExpressionAttributeValues={
                    ":app": service_name,
                    ":cutoff": cutoff_time.isoformat(),
                },
                ScanIndexForward=False,  # Most recent first
                Limit=10,
            )

            items = response.get("Items", [])
            return [
                DeploymentEvent(
                    deployment_id=cast(str, item["deployment_id"]),
                    timestamp=cast(str, item["timestamp"]),
                    application_name=cast(str, item["application_name"]),
                    commit_sha=cast(str, item.get("commit_sha", "unknown")),
                    commit_message=cast(str, item.get("commit_message", "")),
                    argocd_sync_status=cast(
                        str, item.get("argocd_sync_status", "Unknown")
                    ),
                    rollout_status=cast(str, item.get("rollout_status", "Unknown")),
                    image_tag=cast(str, item.get("image_tag", "unknown")),
                    deployed_by=cast(str, item.get("deployed_by", "unknown")),
                    source=cast(str, item.get("source", "unknown")),
                )
                for item in items
            ]
        except Exception as e:
            logger.error(f"Failed to query deployments table: {e}")
            return []

    async def _correlate_with_code_graph(
        self, error_message: Optional[str], stack_trace: Optional[str]
    ) -> list[CodeEntity]:
        """
        Map error messages and stack traces to Neptune code entities.

        This is Aura's unique capability vs AWS DevOps Agent.
        """
        if not error_message and not stack_trace:
            return []

        code_entities = []

        # Extract function names from stack trace
        if stack_trace:
            function_names = self._extract_function_names(stack_trace)
            logger.info(
                f"Extracted {len(function_names)} function names from stack trace"
            )

            # Query Neptune for function nodes (if context service available)
            if self.context and hasattr(self.context, "graph_store"):
                for func_name in function_names:
                    try:
                        entity = await self.context.graph_store.get_entity_by_name(
                            entity_type="function", name=func_name
                        )
                        if entity:
                            code_entities.append(
                                CodeEntity(
                                    entity_id=entity.get("id", ""),
                                    entity_type="function",
                                    name=func_name,
                                    file_path=entity.get("file_path", ""),
                                    line_number=entity.get("line_number"),
                                )
                            )
                    except Exception as e:
                        logger.warning(f"Failed to query Neptune for {func_name}: {e}")

        # Semantic search in OpenSearch for error message (if context service available)
        if error_message and self.context and hasattr(self.context, "vector_store"):
            try:
                similar_code = await self.context.vector_store.semantic_search(
                    query=error_message,
                    top_k=5,
                    filters={"entity_type": "function"},
                )
                for result in similar_code:
                    code_entities.append(
                        CodeEntity(
                            entity_id=result.get("id", ""),
                            entity_type=result.get("entity_type", "unknown"),
                            name=result.get("name", ""),
                            file_path=result.get("file_path", ""),
                            line_number=result.get("line_number"),
                        )
                    )
            except Exception as e:
                logger.warning(f"Failed to search OpenSearch: {e}")

        return code_entities

    def _extract_function_names(self, stack_trace: str) -> list[str]:
        """Parse stack trace to extract function names."""
        # Python stack trace pattern: "in <function_name>"
        # Example: "  File \"/app/src/api.py\", line 45, in handle_request"
        pattern = r"\bin\s+(\w+)"
        matches = re.findall(pattern, stack_trace)
        return list(set(matches))  # Deduplicate

    async def _search_recent_changes(
        self,
        code_entities: list[CodeEntity],
        incident_time: str,
        lookback_days: int = 7,
    ) -> list[GitCommit]:
        """Search OpenSearch for recent commits affecting code entities."""
        incident_dt = datetime.fromisoformat(incident_time.replace("Z", "+00:00"))
        cutoff_time = incident_dt - timedelta(days=lookback_days)

        git_commits = []

        # Search for commits modifying affected files (if context service available)
        if self.context and hasattr(self.context, "vector_store"):
            for entity in code_entities:
                file_path = entity.file_path
                if file_path:
                    try:
                        commits = await self.context.vector_store.search_commits(
                            file_path=file_path, after=cutoff_time
                        )
                        for commit in commits:
                            git_commits.append(
                                GitCommit(
                                    sha=commit.get("sha", ""),
                                    message=commit.get("message", ""),
                                    author=commit.get("author", ""),
                                    timestamp=commit.get("timestamp", ""),
                                    file_path=file_path,
                                )
                            )
                    except Exception as e:
                        logger.warning(f"Failed to search commits for {file_path}: {e}")

        # Deduplicate by commit SHA
        unique_commits = {c.sha: c for c in git_commits}.values()
        return list(unique_commits)

    async def _generate_rca_hypothesis(
        self,
        incident_context: IncidentContext,
        metrics: dict[str, Any],
        deployments: list[DeploymentEvent],
        code_entities: list[CodeEntity],
        git_commits: list[GitCommit],
    ) -> RCAHypothesis:
        """Use LLM to generate root cause analysis hypothesis."""
        if not self.llm:
            logger.warning("No LLM client available, returning default RCA")
            return RCAHypothesis(
                hypothesis="Unable to generate RCA (no LLM client configured)",
                confidence=0,
                evidence=["LLM client not available"],
                alternatives=[],
            )

        prompt = self._build_rca_prompt(
            incident_context=incident_context,
            metrics=metrics,
            deployments=deployments,
            code_entities=code_entities,
            git_commits=git_commits,
        )

        try:
            response = await self.llm.generate(
                prompt=prompt,
                agent="RuntimeIncidentAgent",
                max_tokens=2000,
                operation="rca_generation",  # ADR-015: Uses ACCURATE tier
            )

            # Parse structured response
            rca_result = self._parse_rca_response(response)
            return rca_result
        except Exception as e:
            logger.error(f"Failed to generate RCA hypothesis: {e}")
            return RCAHypothesis(
                hypothesis=f"Error generating RCA: {str(e)}",
                confidence=0,
                evidence=[],
                alternatives=[],
            )

    def _build_rca_prompt(
        self,
        incident_context: IncidentContext,
        metrics: dict[str, Any],
        deployments: list[DeploymentEvent],
        code_entities: list[CodeEntity],
        git_commits: list[GitCommit],
    ) -> str:
        """Construct LLM prompt for RCA generation."""
        return f"""You are a senior SRE investigating a production incident. Analyze the following data and generate a root cause analysis hypothesis.

**Incident Details:**
- Alert: {incident_context.alert_name}
- Service: {incident_context.affected_service}
- Timestamp: {incident_context.timestamp}
- Error Message: {incident_context.error_message or 'N/A'}
- Metric Triggered: {incident_context.metric_name or 'N/A'}
- Severity: {incident_context.severity.value}

**Recent Deployments (Last 24 Hours):**
{self._format_deployments(deployments)}

**Code Entities Involved:**
{self._format_code_entities(code_entities)}

**Recent Code Changes (Last 7 Days):**
{self._format_git_commits(git_commits)}

**Observability Data:**
- CloudWatch Errors: {len(metrics.get('cloudwatch_logs', []))} log entries
- Datadog Traces: {len(metrics.get('datadog_traces', []))} error traces
- CPU Usage: {self._summarize_prometheus_data(metrics.get('prometheus_cpu', {}))}

**Task:**
Generate a root cause analysis hypothesis following this structure:

1. **Hypothesis**: Single sentence describing the likely root cause
2. **Confidence**: Integer 0-100 indicating confidence in this hypothesis
3. **Evidence**: Bulleted list of supporting evidence from the data above
4. **Alternative Hypotheses**: 1-2 alternative explanations if confidence < 80%

Format your response as JSON:
{{
  "hypothesis": "...",
  "confidence": 85,
  "evidence": ["...", "...", "..."],
  "alternatives": ["...", "..."]
}}
"""

    async def _generate_mitigation_plan(
        self, rca_result: RCAHypothesis, recent_deployments: list[DeploymentEvent]
    ) -> str:
        """Generate mitigation plan based on RCA hypothesis."""
        if not self.llm:
            return "Unable to generate mitigation plan (no LLM client configured)"

        prompt = f"""Based on the following root cause analysis, generate a step-by-step mitigation plan.

**RCA Hypothesis:** {rca_result.hypothesis}
**Confidence:** {rca_result.confidence}%
**Evidence:** {', '.join(rca_result.evidence)}

**Recent Deployments:**
{self._format_deployments(recent_deployments)}

**Task:**
Generate a mitigation plan with:
1. Immediate actions to restore service (if applicable)
2. Verification steps to confirm mitigation success
3. Rollback plan if mitigation fails
4. Long-term fixes to prevent recurrence

Format as a numbered list.
"""

        try:
            response = await self.llm.generate(
                prompt=prompt,
                agent="RuntimeIncidentAgent",
                max_tokens=1500,
                operation="mitigation_planning",  # ADR-015: Uses ACCURATE tier
            )
            return cast(str, response)
        except Exception as e:
            logger.error(f"Failed to generate mitigation plan: {e}")
            return f"Error generating mitigation plan: {str(e)}"

    def _format_deployments(self, deployments: list[DeploymentEvent]) -> str:
        """Format deployment data for LLM prompt."""
        if not deployments:
            return "No recent deployments found."

        lines = []
        for d in deployments[:5]:  # Limit to 5 most recent
            lines.append(
                f"- {d.timestamp}: {d.application_name} → {d.image_tag} "
                f"(commit: {d.commit_sha[:7]}, status: {d.rollout_status})"
            )
        return "\n".join(lines)

    def _format_code_entities(self, code_entities: list[CodeEntity]) -> str:
        """Format code entity data for LLM prompt."""
        if not code_entities:
            return "No code entities identified in incident."

        lines = []
        for entity in code_entities[:10]:  # Limit to 10
            lines.append(
                f"- {entity.name} ({entity.entity_type}) in {entity.file_path}"
            )
        return "\n".join(lines)

    def _format_git_commits(self, git_commits: list[GitCommit]) -> str:
        """Format git commit data for LLM prompt."""
        if not git_commits:
            return "No recent code changes affecting incident scope."

        lines = []
        for commit in git_commits[:5]:  # Limit to 5 most recent
            lines.append(
                f"- {commit.timestamp}: {commit.message} "
                f"(SHA: {commit.sha[:7]}, author: {commit.author})"
            )
        return "\n".join(lines)

    def _summarize_prometheus_data(self, prometheus_data: dict[str, Any]) -> str:
        """Summarize Prometheus time series data."""
        if not prometheus_data or "data" not in prometheus_data:
            return "No data"

        try:
            # Calculate avg/max from time series
            values = [
                float(v[1])
                for result in prometheus_data["data"]["result"]
                for v in result.get("values", [])
            ]
            if not values:
                return "No data"

            avg = sum(values) / len(values)
            max_val = max(values)
            return f"avg={avg:.2f}, max={max_val:.2f}"
        except (KeyError, ValueError, ZeroDivisionError):
            return "Invalid data"

    def _parse_rca_response(self, response: str) -> RCAHypothesis:
        """Parse LLM response into structured RCA result."""
        import re

        # Debug: log response length and preview
        if not response or not response.strip():
            logger.error("Empty RCA response from LLM")
            return RCAHypothesis(
                hypothesis="Unable to generate RCA (empty LLM response)",
                confidence=0,
                evidence=["LLM returned empty response"],
                alternatives=[],
            )

        logger.debug(f"Raw RCA response ({len(response)} chars): {response[:200]}...")

        try:
            json_str = response.strip()

            # Try multiple extraction strategies
            # Strategy 1: ```json ... ``` blocks
            if "```json" in response:
                json_start = response.index("```json") + 7
                json_end = response.rindex("```")
                json_str = response[json_start:json_end].strip()
            # Strategy 2: ``` ... ``` blocks
            elif "```" in response:
                json_start = response.index("```") + 3
                json_end = response.rindex("```")
                json_str = response[json_start:json_end].strip()
            # Strategy 3: Find JSON object with regex
            elif "{" in response and "}" in response:
                # Find the outermost JSON object
                match = re.search(r'\{[^{}]*"hypothesis"[^{}]*\}', response, re.DOTALL)
                if not match:
                    # Try more permissive pattern for nested objects
                    match = re.search(r'\{.*?"hypothesis".*?\}', response, re.DOTALL)
                if match:
                    json_str = match.group(0)

            result = json.loads(json_str)

            # Validate required fields
            if "hypothesis" not in result or "confidence" not in result:
                raise ValueError("Missing required fields in RCA response")

            # Ensure confidence is in valid range
            confidence = max(0, min(100, int(result["confidence"])))

            logger.info(
                f"Parsed RCA: {result['hypothesis'][:100]}... (confidence: {confidence}%)"
            )

            return RCAHypothesis(
                hypothesis=result["hypothesis"],
                confidence=confidence,
                evidence=result.get("evidence", []),
                alternatives=result.get("alternatives", []),
            )
        except json.JSONDecodeError as e:
            logger.error(f"Failed to parse RCA JSON: {e}")
            logger.error(
                f"Attempted to parse: {json_str[:500] if json_str else 'empty'}..."
            )
            # Try to extract hypothesis from plain text response
            if "hypothesis" in response.lower():
                return RCAHypothesis(
                    hypothesis=f"RCA (raw): {response[:500]}",
                    confidence=30,
                    evidence=["Parsed from non-JSON response"],
                    alternatives=[],
                )
            return RCAHypothesis(
                hypothesis="Unable to determine root cause (JSON parsing error)",
                confidence=0,
                evidence=[str(e), f"Response preview: {response[:200]}"],
                alternatives=[],
            )
        except Exception as e:
            logger.error(f"Failed to parse RCA response: {e}")
            return RCAHypothesis(
                hypothesis="Unable to determine root cause (parsing error)",
                confidence=0,
                evidence=[str(e)],
                alternatives=[],
            )

    # Helper methods for dict conversion
    def _deployment_to_dict(self, deployment: DeploymentEvent) -> dict[str, Any]:
        """Convert DeploymentEvent to dictionary."""
        return {
            "deployment_id": deployment.deployment_id,
            "timestamp": deployment.timestamp,
            "application_name": deployment.application_name,
            "commit_sha": deployment.commit_sha,
            "commit_message": deployment.commit_message,
            "argocd_sync_status": deployment.argocd_sync_status,
            "rollout_status": deployment.rollout_status,
            "image_tag": deployment.image_tag,
            "deployed_by": deployment.deployed_by,
            "source": deployment.source,
        }

    def _code_entity_to_dict(self, entity: CodeEntity) -> dict[str, Any]:
        """Convert CodeEntity to dictionary."""
        return {
            "entity_id": entity.entity_id,
            "entity_type": entity.entity_type,
            "name": entity.name,
            "file_path": entity.file_path,
            "line_number": entity.line_number,
            "namespace": entity.namespace,
            "dependencies": entity.dependencies,
        }

    def _git_commit_to_dict(self, commit: GitCommit) -> dict[str, Any]:
        """Convert GitCommit to dictionary."""
        return {
            "sha": commit.sha,
            "message": commit.message,
            "author": commit.author,
            "timestamp": commit.timestamp,
            "file_path": commit.file_path,
            "changes_summary": commit.changes_summary,
        }
