{{- if and (include "aura.isSelfHosted" .) .Values.databases.vector.opensearch.enabled }}
{{- if not .Values.databases.vector.opensearch.existingPasswordSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aura.fullname" . }}-opensearch
  labels:
    {{- include "aura.componentLabels" (dict "component" "opensearch" "context" .) | nindent 4 }}
type: Opaque
data:
  {{- if .Values.databases.vector.opensearch.adminPassword }}
  admin-password: {{ .Values.databases.vector.opensearch.adminPassword | b64enc | quote }}
  {{- else }}
  admin-password: {{ randAlphaNum 24 | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
