"""
Tests for scripts/security_hooks/commit_msg_hook.py.

Closes #163 HIGH item: "No test coverage for commit_msg_hook.py".

Covers:
- Standard Co-Authored-By stripping
- Versioned Claude variants (Opus/Sonnet/Haiku)
- "Generated with Claude Code" markdown + plain forms
- Robot emoji + Claude lines
- Idempotence (running twice is a no-op)
- Multi-paragraph commit bodies preserved
- File-not-found and empty-message handling
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest

# Load the hook module by path (it's a script, not a package).
_HOOK_PATH = (
    Path(__file__).parent.parent.parent
    / "scripts"
    / "security_hooks"
    / "commit_msg_hook.py"
)
_spec = importlib.util.spec_from_file_location("commit_msg_hook", _HOOK_PATH)
commit_msg_hook = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(commit_msg_hook)


# ---------------------------------------------------------------------------
# strip_ai_attribution unit tests
# ---------------------------------------------------------------------------


class TestStripCoAuthoredBy:
    """Co-Authored-By lines for Claude must be stripped."""

    def test_strips_basic_co_authored_by(self):
        msg = (
            "feat: add thing\n"
            "\n"
            "Co-Authored-By: Claude <noreply@anthropic.com>\n"
        )
        cleaned, removed = commit_msg_hook.strip_ai_attribution(msg)
        assert removed == 1
        assert "Claude" not in cleaned
        assert "Co-Authored-By" not in cleaned
        assert "feat: add thing" in cleaned

    def test_strips_versioned_claude_variants(self):
        for variant in (
            "Claude Opus 4.5",
            "Claude Opus 4.7",
            "Claude Sonnet 4.6",
            "Claude Haiku 4.5",
            "Claude 3.5",
        ):
            msg = f"fix: bug\n\nCo-Authored-By: {variant} <noreply@anthropic.com>\n"
            cleaned, removed = commit_msg_hook.strip_ai_attribution(msg)
            assert removed == 1, f"failed to strip variant: {variant}"
            assert variant not in cleaned

    def test_strips_case_insensitive(self):
        msg = (
            "feat: thing\n"
            "\n"
            "co-authored-by: claude <user@anthropic.com>\n"
        )
        cleaned, removed = commit_msg_hook.strip_ai_attribution(msg)
        assert removed == 1
        assert "claude" not in cleaned

    def test_keeps_other_co_authors(self):
        msg = (
            "feat: pair-programmed\n"
            "\n"
            "Co-Authored-By: Alice <alice@example.com>\n"
            "Co-Authored-By: Claude <noreply@anthropic.com>\n"
        )
        cleaned, removed = commit_msg_hook.strip_ai_attribution(msg)
        assert removed == 1
        assert "Alice <alice@example.com>" in cleaned
        assert "Claude" not in cleaned


class TestStripGeneratedWithLines:
    """'Generated with Claude Code' lines (markdown + plain) must be stripped."""

    def test_strips_markdown_generated_with(self):
        msg = (
            "feat: add doc\n"
            "\n"
            "🤖 Generated with [Claude Code](https://claude.com/claude-code)\n"
        )
        cleaned, removed = commit_msg_hook.strip_ai_attribution(msg)
        assert removed >= 1
        assert "Claude Code" not in cleaned

    def test_strips_plain_text_generated_with(self):
        msg = "chore: bump\n\nGenerated with Claude Code\n"
        cleaned, removed = commit_msg_hook.strip_ai_attribution(msg)
        assert removed >= 1
        assert "Generated with Claude Code" not in cleaned

    def test_strips_generated_by_claude(self):
        msg = "feat: x\n\nThis was generated by Claude Opus.\n"
        cleaned, removed = commit_msg_hook.strip_ai_attribution(msg)
        assert removed >= 1
        assert "generated by Claude" not in cleaned.lower()

    def test_strips_robot_emoji_claude_line(self):
        msg = "fix: y\n\n🤖 Powered by Claude\n"
        cleaned, removed = commit_msg_hook.strip_ai_attribution(msg)
        assert removed >= 1
        assert "Claude" not in cleaned


class TestIdempotence:
    """Running the stripper twice must be a no-op on the second pass."""

    def test_idempotent_run(self):
        msg = (
            "feat: thing\n"
            "\n"
            "Co-Authored-By: Claude <noreply@anthropic.com>\n"
            "🤖 Generated with [Claude Code](https://claude.com/claude-code)\n"
        )
        cleaned_once, removed_first = commit_msg_hook.strip_ai_attribution(msg)
        cleaned_twice, removed_second = commit_msg_hook.strip_ai_attribution(
            cleaned_once
        )
        assert removed_first >= 2
        assert removed_second == 0
        assert cleaned_once == cleaned_twice


class TestPreservesContent:
    """Stripping must not damage non-AI content."""

    def test_preserves_multiparagraph_body(self):
        body = (
            "feat(scanner): wire up X\n"
            "\n"
            "Implements the Y behavior described in ADR-099.\n"
            "Now does Z when triggered by W.\n"
            "\n"
            "Closes #1234.\n"
            "\n"
            "Co-Authored-By: Claude <noreply@anthropic.com>\n"
        )
        cleaned, removed = commit_msg_hook.strip_ai_attribution(body)
        assert removed == 1
        assert "Implements the Y behavior" in cleaned
        assert "Closes #1234." in cleaned
        # Excess blank lines should be collapsed but content preserved.
        assert "feat(scanner): wire up X" in cleaned

    def test_clean_message_passes_through(self):
        msg = "feat: nothing to strip\n\nBody line.\n"
        cleaned, removed = commit_msg_hook.strip_ai_attribution(msg)
        assert removed == 0
        assert "feat: nothing to strip" in cleaned
        assert "Body line." in cleaned

    def test_excessive_blank_lines_collapsed(self):
        msg = "feat: x\n\n\n\n\nBody\n"
        cleaned, _ = commit_msg_hook.strip_ai_attribution(msg)
        assert "\n\n\n" not in cleaned

    def test_trailing_whitespace_stripped(self):
        msg = "feat: x\n\nBody   \n   \n"
        cleaned, _ = commit_msg_hook.strip_ai_attribution(msg)
        assert cleaned.endswith("\n")
        assert not cleaned.endswith("   \n")


# ---------------------------------------------------------------------------
# main() integration via a temp commit-msg file
# ---------------------------------------------------------------------------


class TestMain:
    """End-to-end behavior of the hook entry point."""

    def test_main_strips_in_place(self, tmp_path, monkeypatch):
        commit_msg = tmp_path / "COMMIT_EDITMSG"
        commit_msg.write_text(
            "feat: a thing\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n",
            encoding="utf-8",
        )
        monkeypatch.setattr(sys, "argv", ["commit_msg_hook.py", str(commit_msg)])
        rc = commit_msg_hook.main()
        assert rc == 0
        cleaned = commit_msg.read_text(encoding="utf-8")
        assert "Claude" not in cleaned
        assert "feat: a thing" in cleaned

    def test_main_no_attribution_passes_unchanged(self, tmp_path, monkeypatch):
        commit_msg = tmp_path / "COMMIT_EDITMSG"
        original = "fix: clean message\n\nNothing to strip.\n"
        commit_msg.write_text(original, encoding="utf-8")
        monkeypatch.setattr(sys, "argv", ["commit_msg_hook.py", str(commit_msg)])
        rc = commit_msg_hook.main()
        assert rc == 0
        assert commit_msg.read_text(encoding="utf-8") == original

    def test_main_missing_file_returns_zero(self, tmp_path, monkeypatch):
        """A missing commit-msg file must not block the commit."""
        missing = tmp_path / "does_not_exist"
        monkeypatch.setattr(sys, "argv", ["commit_msg_hook.py", str(missing)])
        rc = commit_msg_hook.main()
        assert rc == 0

    def test_main_no_argv_returns_zero(self, monkeypatch):
        """Hook must not raise when invoked without args."""
        monkeypatch.setattr(sys, "argv", ["commit_msg_hook.py"])
        rc = commit_msg_hook.main()
        assert rc == 0

    def test_main_empty_file_returns_zero(self, tmp_path, monkeypatch):
        commit_msg = tmp_path / "COMMIT_EDITMSG"
        commit_msg.write_text("", encoding="utf-8")
        monkeypatch.setattr(sys, "argv", ["commit_msg_hook.py", str(commit_msg)])
        rc = commit_msg_hook.main()
        assert rc == 0


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
